Add AgentCommand functionality and AgentHealth Endpoint
inspectIT/inspectit-ocelot pull request #1055
Opened 2021-04-27 06:08 UTC by MariusBrill

2021-05-05 07:15 UTC, mariusoe requested changes
> Reviewed 15 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: 15 of 22 files reviewed, 24 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 52 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNqE7i0Pml-eRN3m6_:-MZNqE7i0Pml-eRN3m6a:bfr5hxb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L52)):*
> ```Java
>     private AgentCallbackManager agentCallbackManager;
> 
>     private ObjectWriter objectWriter = new ObjectMapper().writer().withDefaultPrettyPrinter();
> ```

Not used.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 107 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQ4P5Bg3MUn8mlar6:-MZqQ4P5Bg3MUn8mlar7:bz3p3xf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L107)):*
> ```Java
>      * is not.
>      */
>     @PostMapping(value = "agent/health", produces = "text/plain")
> ```

Why do you use `POST`?  This endpoint should return the agent status - we don't want to send and use data here. So let's use a `GET` endpoint instead.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 108 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQgB39eLV2duTf7pi:-MZqQgB39eLV2duTf7pj:b-rlss6u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L108)):*
> ```
> ?
> ```
Please use a specific type.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 109 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQLFV4EFK6fFocSNF:-MZqQLFV4EFK6fFocSNG:b-yhxokq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L109)):*
> ```Java
>     @PostMapping(value = "agent/health", produces = "text/plain")
>     public ResponseEntity<?> getHealth(@RequestHeader Map<String, String> headers) throws ExecutionException {
>         String agentID = headers.get("x-ocelot-agent-id");
> ```

Let's use query parameters instead of headers. Query parameters are much more common and easier to use than header attributes.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 115 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqT59tEBeplRaW1YKA:-MZqT59tEBeplRaW1YKB:b-fjoyf9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L115)):*
> ```Java
>         DeferredResult<?> deferredResult = agentCommandDelegator.runCommand(command);
> 
>         return (ResponseEntity<?>) deferredResult.getResult();
> ```

Actually, you can directly return the deferred result. As soon it is getting resovled (the result is set), the servlet will continue its processing.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/SecurityConfiguration.java, line 59 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNdDMNAx14MxHolO_n:-MZNdDMNAx14MxHolO_o:b8u7hdt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/SecurityConfiguration.java#L59)):*
> ```Java
>     public void configure(WebSecurity web) {
>         web.ignoring()
>                 .antMatchers("/v2/api-docs", "/configuration/**", "/csrf", "/", "/ui/**", "/actuator/**", "/swagger*/**", "/webjars/**", "/api/v1/agent/configuration", "/api/v1/agent/command");
> ```

Can you revert this formatting
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java, line 17 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNsQ1W61MU9yHk7Qaw:-MZNsQ1W61MU9yHk7Qax:be4b41s) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java#L17)):*
> ```
> Delegator
> ```
`Dispatcher`?
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java, line 31 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNqR-kB7P1OZkRDvRs:-MZNqR-kB7P1OZkRDvRt:bg6j0vq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java#L31)):*
> ```Java
>      */
>     public DeferredResult<?> runCommand(AgentCommand agentCommand) throws ExecutionException {
>         for (CommandHandler handler : handlers) {
> ```

We should know which handler is capabale of executing a certain command. So, the handler should state which type of command it supports instead of passing the command to each one, until we receive a result.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/CommandHandler.java, line 8 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNpEyi4-Iju3luqjzk:-MZNpEyi4-Iju3luqjzl:bv9foht) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/CommandHandler.java#L8)):*
> ```Java
> import java.util.concurrent.ExecutionException;
> 
> public interface CommandHandler {
> ```

Please see the `AgentResponse/Command` class and their comments.

I would propose that we introduce "base" classes for the payload and responses and each command should implement a custom one if necessary.
Then, we can make this handler generic and pass concrete class instances instead of these high level classes.

E.g.:

```
public interface CommandHandler<T extends AgentCommand, U extends AgentResponse> {
    DeferredResult<U> handleCommand(T agentCommand) throws ExecutionException;
}
```

Each handler can then decide which type of command it can process.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/handlersimpl/HealthCommandHandler.java, line 1 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqOtH89FtEI-Pprl03:-MZqOtH9-lqQa4WYzdu6:b8yuz97) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/handlersimpl/HealthCommandHandler.java#L1)):*
> ```
> handlersimpl
> ```
Please try to prevent multiple word within a package name. Just name it `impl`
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/ [...]

2021-05-05 08:22 UTC, mariusoe requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: 15 of 22 files reviewed, 26 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java, line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZvWmTMBnwActNp_m0c:-MZvWmTN6NiISLXMLxWP:b-lobpbr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java#L61)):*
> ```
> runNextCommandWithId
> ```
maybe we should rename this method
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java, line 64 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZvbkKA7PWfE6v9wtq1:-MZvbkKBClyTLqFS4Hxz:b-pzs901) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java#L64)):*
> ```Java
>         if (ObjectUtils.allNotNull(agentID, commandID)) {
> 
>             String identifier = agentID + commandID.toString();
> ```

UUID is already unique


<!-- Sent from Reviewable.io -->

2021-05-25 09:56 UTC, MariusBrill reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: 10 of 30 files reviewed, 26 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 52 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNqE7i0Pml-eRN3m6_:-MaXwA-2CqjSS23JKJH4:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L52)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 107 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQ4P5Bg3MUn8mlar6:-MaXwAhcDMdKw4Y6TtBq:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L107)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Why do you use `POST`?  This endpoint should return the agent status - we don't want to send and use data here. So let's use a `GET` endpoint instead.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 108 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQgB39eLV2duTf7pi:-MaXwOUN9X10VXA4snHL:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L108)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> ?
> ```
Please use a specific type.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 109 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqQLFV4EFK6fFocSNF:-MaXwLWo2HegOrNxwuWl:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L109)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's use query parameters instead of headers. Query parameters are much more common and easier to use than header attributes.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java, line 115 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZqT59tEBeplRaW1YKA:-MaXwMIT9L0Vsp-KAJEx:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java#L115)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Actually, you can directly return the deferred result. As soon it is getting resovled (the result is set), the servlet will continue its processing.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/SecurityConfiguration.java, line 59 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNdDMNAx14MxHolO_n:-MaXwdi3Ccn0Rrm4pnjC:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/SecurityConfiguration.java#L59)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you revert this formatting
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java, line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZvWmTMBnwActNp_m0c:-MaXv_PL9Uk0vjvxebbI:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java#L61)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> runNextCommandWithId
> ```
maybe we should rename this method
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java, line 64 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZvbkKA7PWfE6v9wtq1:-MaXv_rY-Zo9mWr1AGL5:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCallbackManager.java#L64)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

UUID is already unique
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java, line 17 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNsQ1W61MU9yHk7Qaw:-MaXvc7c4glj_npvUbMM:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java#L17)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> Delegator
> ```
`Dispatcher`?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java, line 31 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNqR-kB7P1OZkRDvRs:-MaXvd09DM8_grqZgfQz:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandDelegator.java#L31)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

We should know which handler is capabale of executing a certain command. So, the handler should state which type of command it supports instead of passing the command to each one, until we receive a result.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/CommandHandler.java, line 8 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-MZNpEyi4-Iju3luqjzk:-MaXvfsZ7IibQSE2Wanp:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e3ede0c048ffd13e1a6d59a2e5264a4d7db557e7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/CommandHandler.java#L8)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please see the `AgentResponse/Command` class and their comments.

I would propose that we introduce "base" classes for the payload and responses and each command should impl [...]

2021-05-31 09:29 UTC, Patrick-Eichhorn requested changes
> Reviewed 20 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: 29 of 30 files reviewed, 27 unresolved discussions (waiting on @MariusBrill and @mariusoe)

___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/impl/PingCommand.java, line 5 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-Mb0jIgw7MbfjqpbnhW_:-Mb0jIgx0B6xpS2CE8GT:b-pbx9dq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4d4fd02ab30b287deecff0d7b38e7023b3a64e59/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/impl/PingCommand.java#L5)):*
> ```Java
> import lombok.Value;
> import rocks.inspectit.ocelot.commons.models.command.Command;
> ```

Can you describe what it is used for? (health check)


<!-- Sent from Reviewable.io -->

2021-05-31 13:40 UTC, MariusBrill reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: 26 of 30 files reviewed, 27 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/impl/PingCommand.java, line 5 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-Mb0jIgw7MbfjqpbnhW_:-Mb1dcUm1JRMQQKrMt4t:b-yb72c8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4d4fd02ab30b287deecff0d7b38e7023b3a64e59/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/impl/PingCommand.java#L5)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Can you describe what it is used for? (health check)
</blockquote></details>

Also added description for PingResponse


<!-- Sent from Reviewable.io -->

2021-06-02 08:01 UTC, mariusoe reviewed
> Reviewed 10 of 21 files at r4, 1 of 3 files at r5, 16 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: all files reviewed, 27 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)



<!-- Sent from Reviewable.io -->

2021-06-02 08:02 UTC, mariusoe approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055#-:-MbAjO2c1zL5u68PVH8u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)



<!-- Sent from Reviewable.io -->

2021-06-02 09:14 UTC, Patrick-Eichhorn approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1055)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)



<!-- Sent from Reviewable.io -->

2021-06-02 09:19 UTC, merged