Add functionality to cache directories & distinguish between ui- and "normal" files.
inspectIT/inspectit-ocelot pull request #1117
Opened 2021-06-22 10:11 UTC by MariusBrill

2021-06-23 13:35 UTC, mariusoe requested changes
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117)* status: 2 of 12 files reviewed, 20 unresolved discussions (waiting on @MariusBrill and @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-McszjKA5vm71u6EP18S:-McszjKB1U4ljl8lu0m9:b-pz8xwk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L20)):*
> ```
> 10 for each directory
> ```
for each commit
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-McszmtMBzr2zrxzBtkM:-McszmtN8drIT13rEHFR:b4895i3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L20)):*
> ```
> directory has changed
> ```
directory's content has been modified
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct-3KOBeXbjukAMTYv:-Mct-3KOBeXbjukAMTYw:bgs05n9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L29)):*
> ```Java
>      * Timeout used for the LoadingCaches.
>      */
>     private final long CACHE_TIMEOUT = 86400000L; //One day as millis.
> ```

`Duration.ofDays(1);` makes it easier and can directly be used in the builder ;)
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct-XAW6PmnhXcx6omZ:-Mct-XAW6PmnhXcx6om_:b-u9xena) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L29)):*
> ```Java
>      * Timeout used for the LoadingCaches.
>      */
>     private final long CACHE_TIMEOUT = 86400000L; //One day as millis.
> ```

can be `static`
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 34 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct-ZKv8eGmvSFcO35F:-Mct-74F1Orr7AGK7v8B:b-x1tlxx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L34)):*
> ```Java
>      * Size used for the LoadingCaches.
>      */
>     private final long CACHE_SIZE = 10;
> ```

Can also be `static`
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 59 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct36942WgsjeNuOavX:-Mct36942WgsjeNuOavY:b9kox6y) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L59)):*
> ```
> working
> ```
Currently, we use the term `workspace` in different classes to reference this branch. Let's make it consistent and use `wrokspace`.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 74 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct01Kr4K5Z5iaLll_d:-Mct01Kr4K5Z5iaLll_e:b-re2ihx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L74)):*
> ```Java
>     /**
>      * Generates a LoadingCache based on the given directory string. Valid values for the directory String is either
>      * "working", "live" or a commit id.
> ```

Check your formatter. There something wrong here. There should be an empty line between the description and parameters.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct08-F0J-7gyNla_0f:-Mct08-F0J-7gyNla_0g:bc61qpc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L78)):*
> ```
> generateLoadingCache
> ```
How about `createCache`? 
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct0JcA3dVrrYHx4gjj:-Mct0JcA3dVrrYHx4gjk:b-2yxe1q) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L78)):*
> ```
> String directory
> ```
It's a commit and not a directory. See last comment in the file.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 79 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct0C_kDOe8fmD1XgKR:-Mct0C_kDOe8fmD1XgKS:bavx37l) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L79)):*
> ```Java
>      */
>     private LoadingCache<String, List<FileInfo>> generateLoadingCache(String directory) {
>         Function<String, List<FileInfo>> listFiles = path -> fileManager.getCommitWithId(directory).listConfigurationFiles(path);
> ```

Can you restructure this a bit, so we don't have to create this lambda in case the commit is `working` or `live`?

```
final Function listFilesFunction;
if ("working") {
  listFilesFunction = ...
} else if ("live") {
  listFilesFunction = ...
} else {
  listFilesFunction = ...
} 
```

Then you don't have to create a final var just for the anonymous class.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 79 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct0Zqv7c4UlsSJth_X:-Mct0Zqv7c4UlsSJth_Y:bvezfn5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L79)):*
> ```
> listFiles
> ```
Can you name it `listFilesFunction`?
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 107 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct1ShR6QpU3zl_u-Fz:-Mct1ShR6QpU3zl_u-G-:b-xtwsl7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L107)):*
> ```
> directory
> ```
Again `commit`
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 107 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct2isg [...]

2021-07-01 09:54 UTC, mariusoe requested changes
> Reviewed 5 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117)* status: 5 of 19 files reviewed, 25 unresolved discussions (waiting on @MariusBrill and @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 83 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWLN1M2Q5zHo6vhvvA:-MdWLN1M2Q5zHo6vhvvB:b-5952mz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L83)):*
> ```Java
>             Type type = new TypeToken<Map<String, String>>(){}.getType();
>             //Remove comment-character from line.
>             String firstLine = fileScanner.nextLine().replace("#", "");
> ```

This could lead to problems if  `#` are used somewhere in the object.
I would propose to just trim the string and remove the leading '#'. `trim().substring(1);`
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 86 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWLAfE8advrYKnjiHT:-MdWLAfFAxzZEOr-U9pd:b-1ip0e0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L86)):*
> ```
> new Gson()
> ```
Gson is thread-safe, so you can reuse an instance of this instead of recreating it each time.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 92 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWM7dv5i7AkRnUn8au:-MdWM7dv5i7AkRnUn8av:b6sfg8g) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L92)):*
> ```Java
>                     fileType = FileInfo.Type.valueOf(typeString);
>                 }
> ```

Please remove this empty line.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java, line 23 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWMNomD4HqOH2S4GPl:-MdWMNomD4HqOH2S4GPm:b-eoyys) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java#L23)):*
> ```
> CachingDirectoryProxy
> ```
Can we name it just `CachingWorkingDirectoryAccessor`?
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java, line 29 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWMWIQ9U3Tfh18MTBx:-MdWMWIQ9U3Tfh18MTBy:bo18moc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java#L29)):*
> ```Java
>      */
>     private static final Duration TIMEOUT_DURATION = Duration.ofDays(1);
>     /**
> ```

Please format the file using the formatter.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java, line 41 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWOdek4FnWXYladCO9:-MdWOdek4FnWXYladCOA:b-jvee0l) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java#L41)):*
> ```Java
>     LoadingCache<String, List<FileInfo>> workspaceCache;
> 
>     private final AutoCommitWorkingDirectoryProxy autoCommitWorkingDirectoryProxy;
> ```

Doing this, we have a hard dependency on the referenced class. But it would be better when we use just the `AbstractWorkingDirectoryAccessor` here.
This way, we can basically pass any implementation of the `AbstractWorkingDirectoryAccessor` to this decorator and cache some stuff.

The visibility is also no problem, because we dont need the protected methods. We can just override the `public` ones and delegate all invocations to the given target instance.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java, line 60 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWOTJW6wjGBRzKXlBq:-MdWOTJXCGpS577TeDmb:b-8bwzw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingDirectoryProxy.java#L60)):*
> ```Java
>      * Invalidates the current cache.
>      */
>     public void invalidate(){
> ```

`invalidateCache`
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java, line 94 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWR25zCAmwLJgCKEhi:-MdWR26-9q-6mW_AEDc_:bun3uxi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java#L94)):*
> ```Java
>         versioningManager.initialize();
> 
>         ((CachingDirectoryProxy) fileManager.getWorkingDirectory()).invalidate();
> ```

Comment for u.


<!-- Sent from Reviewable.io -->

2021-07-12 06:47 UTC, MariusBrill reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117)* status: 2 of 20 files reviewed, 25 unresolved discussions (waiting on @MariusBrill and @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfo.java, line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct1bmm5enw3diyhcS9:-Mcwl57U1l7iTZDu7fLB:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfo.java#L26)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's use enums corresponding to the "file type". So in this case `method-configuration`. Maybe we can just name the enums something like `UI_XXX`: `UI_METHOD_CONFIGURATION`.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 25 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct1vp-5df8MelsuaN5:-Mcx040Q4MGRmjDJEzQJ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L25)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

This string should not be static because it can change (multiple file types) or contain more data. It is significantly  more overhead but let's parse this line (in case it is a comment) using Gson and extract the `type` property of the resulting Json object. Due to the fact that we use the cache, it should be fine I would gess :) 
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct2HrlC22CfUfic2Cx:-Mcx05Ro-Z--7Iid_7mR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L71)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

See the comment above. The string can change, e.g. we could add more types so we have to be able to handle this.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 83 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWLN1M2Q5zHo6vhvvA:-MdpJwrW8wY6NFYhQ6_g:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L83)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

This could lead to problems if  `#` are used somewhere in the object.
I would propose to just trim the string and remove the leading '#'. `trim().substring(1);`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 86 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWLAfE8advrYKnjiHT:-MdpJxMw-xJTMXd_Hghz:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L86)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> new Gson()
> ```
Gson is thread-safe, so you can reuse an instance of this instead of recreating it each time.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java, line 92 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWM7dv5i7AkRnUn8au:-MdpJzBgEYQQRD_Umzjt:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java#L92)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please remove this empty line.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java, line 94 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-MdWR25zCAmwLJgCKEhi:-MeOTA5-Dd71mwh8IMBh:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4149ba0ef505a17433f65fe36fb9bf411f71fc40/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java#L94)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Comment for u.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-McszjKA5vm71u6EP18S:-Mcwk3GY6oTIohX22Eke:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L20)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> 10 for each directory
> ```
for each commit
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-McszmtMBzr2zrxzBtkM:-McwkCw924Aq9td6VbmT:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L20)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> directory has changed
> ```
directory's content has been modified
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct-3KOBeXbjukAMTYv:-McwkDXvAFA02FvcUyAB:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L29)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

`Duration.ofDays(1);` makes it easier and can directly be used in the builder ;)
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117#-Mct-XAW6PmnhXcx6omZ:-McwkLVbALGyqCOxAdhO:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ce90a6440b4977c3811e027d8af8d147acad8b33/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java#L29)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

can be `static`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/DirectoryCache.java, line 34 at r1](https://reviewable.i [...]

2021-07-12 14:23 UTC, mariusoe submitted a review, later dismissed
> Reviewed 11 of 19 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)



<!-- Sent from Reviewable.io -->

2021-07-12 14:24 UTC, mariusoe approved these changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)



<!-- Sent from Reviewable.io -->

2021-07-12 14:27 UTC, merged