Closes #1246 integrate oc otel bridge
inspectIT/inspectit-ocelot pull request #1270
Opened 2022-01-11 15:01 UTC by heiko-holz

2022-01-11 15:13 UTC, heiko-holz commented
# Important changes introduced with [ticket 1246 - Integrate OpenCensus-OpenTelemetry-Bridge](https://github.com/inspectIT/inspectit-ocelot/issues/1246)

Date: 2022-01-11  
Author: [Heiko Holz](https://github.com/heiko-holz)

With [ticket 1246](https://github.com/inspectIT/inspectit-ocelot/issues/1246), we have added the [`io.opentelemetry-opencensusshim`](https://github.com/open-telemetry/opentelemetry-java/tree/main/opencensus-shim) to inspectIT Ocelot to start the migration from OpenCensus to OpenTelemetry.

As a first step, we added the `opentelemetry-opencensusshim` and implemented a `LoggingMetricsExporterService` and `LoggingTraceExporterService` that export traces and metrics to the system log. To make the migration work, several test cases and methods had to be adjusted to work with OpenTelemetry.  
The most important changes are listed in the following chapters.

> **Important note**:  
> The current version only works with Java 8 and Java 9, as the reflection we are using to reset `io.opentelemetry.opencensusshim.OpenTelemetrySpanBuilderImpl` requires to set the `private final field OTEL_TRACER`. This reflection code is not supported in Java 11 or higher, see https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12. If we want to support Java 10 or higher while still using the opencensusshim, we need to adjust the reflection code in `rocks.inspectit.ocelot.utils.TestUtils#initializeOpenTelemetryForSystemTesting` and in `rocks.inspectit.ocelot.core.utils.ReflectionUtils`
 
## Updated trace and metric exporters

Several trace and metric exporters have been disabled, removed, or added. Disabled services will be enabled in future releases when they have been properly integrated with OpenTelemetry.

### Trace exporters

|Exporter|Working|
|---|---|
|Logging Exporter| &check;
|Jaeger (Thrift)|&cross;
|Zipkin|&cross;

The `OpenCensus Agent Exporter` has been completely removed.

### Metric exporters

|Exporter|Working|
|---|---|
|Logging Exporter| &check;
|Prometheus Exporter|&cross;
|InfluxDB Exporter|&cross;

The `OpenCensus Agent Exporter` has been completely removed.

## Things that have been removed or don't work anymore

The following functions have been removed or are not functional anymore (i.e., they are still in the source code but the tests fail and were disabled)

1. `OpenCensusAgentMetricsExporterService` and `OpenCensusAgentTracingExporterService` have been removed, as 
    - `OcAgentMetricsExporter` and `OcAgentTraceExporter` do not exist in the shim
    - the related tests `OpenCensusAgentMetricsExporterServiceIntTest.java` and `OpenCensusAgentTraceExporterServiceIntTest.java` have also been removed
    - there is no counterpart for OTEL (i.e., no such `OtelAgentMetricsExporter`)
2. `CustomSpanBuilder` does not work anymore as it was using OC's `TracerImpl` via reflection. This breaks when using the shim, which uses the `OpenTelemetryTracerImpl`
   - the `spanBuilderOptions` (`io.opentelemetry.opencensusshim.Options`) of `OpenTelemetrySpanBuilderImpl` do not offer the `startEndHandler` as OC did (`io.opencensus.implcore.trace.SpanBuilderImpl.Options`)
   - further, OTEL does not use the `RecordEventsSpanImpl` that OC uses (the OTEL counterpart is `OpenTelemetrySpanImpl`)
      - we are therefore missing the `TimeConverter` and the `StartEndHandler`
    - &rarr; As a result, we disabled the `CustomSpanBuilderTest`
3. `AutoTracing`/ StackTraceSampling does not work anymore as this expects a functional `CustomSpanBuilder`
   - &rarr; As a result, we disabled the `AutoTracingTest`
4. `InfluxExporterService` does not work anymore
   - potentially, [opencensus-influx-exporter](https://github.com/NovatecConsulting/opencensus-influx-exporter) needs to be re-implemented for OTEL
   - &rarr; The `InfluxExporterServiceIntTest` is still disabled
5. The attribute `serviceName` of the metrics and trace exporters is not supported in OTEL. In OTEL, we can only set the service name for the `SdkMeterProvider` and `OpenTelemetrySdk`

## Things that changed

The following chapters list the most important changes that needed to be considered to make the migration from OpenCensus to OpenTelemetry work.

### Global Trace Export Component

The previously used `io.opentelemetry.trace.Tracing#getTracingComponent()` always returns a `NoopSpanExporter` in `OpenTelemetryTraceComponentImpl.java`. Thus, it was necessary to adjust `TraceTestBase.java` and `TestUtils.java` to build and register a `GlobalOpenTelemetry` with an `InMemorySpanExporter` whose exported traces can be used in the tests.

However, the `InMemorySpanExporter` returns `io.opentelemetry.sdk.trace.data.SpanData`. Thus, changes were applied to the following tests to work again:

- `TraceTestBase.java`
- `TestUtils.java`
- `HttpRemoteTracingTest.java`
- `JigsawTest.java`
- `TraceSettingsTest.java`

### `Span` and related classes

 The main relevant changes from `io.opencensus.trace.Span`  to `io.opentelemetry.api.trace.Span` and related classes are listed in the following:

- `SpanId` may be invalid but not null in OTEL, i.e., when the `io.opencensus.trace.SpanId` was null before, the `io.opentelemetry.api.trace.SpanId` may be now **not** null but invalid. Thus, we should check with `SpanId.isValid(spanId)`:

   ```Java
   // old OC code
   if (span.getParentSpanId.isNull()){
      // do something
   }

   // new OTEL code
   if(SpanId.isValid(span.)){
      // do something
   }
   ```
- a `Span` that was previously a `BlankSpan.INSTANCE` may now be simply invalid
  - in code where we previously checked if a (parent) span is `BlankSpan.INSTANCE`, we now need to check whether the span is valid, i.e.,
  ```Java
   // old code
   if(span == BlankSpan.INSTANCE){
      // do something
   }

   // new code
   if((span == BlankSpan.INSTANCE || !span.getContext().isValid())){
      // do something
   }
  ```
- OpenCensus `io.opencensus.trace.Status` in `Span#getStatus` is replaced by `io.opentelemetry.sdk.trace.data.StatusData`
   - Mapping: 
      |OC `Status`|OTEL `StatusData`| 
      |----|----|
      |`Status.OK`|`StatusData.unset()`|
      |`Status.UNKNOWN`|`StatusData.error()`
  
- OpenCensus `io.opencensus.trace.export.SpanData` is replaced by `io.opentelemetry.sdk.trace.data.SpanData`
  - `getStartTimestamp` and `getEndTimestamp` are replaced by `getStartEpochNanos` and `getEndEpochNanos`, respectively
- `Attributes` are stored differently.
  - The `io.opencensus.trace.export.Attributes#getAttributeMap` is a `Map<String, AttributeValue`, i.e., keys are `String` and values are `io.opencensus.trace.AttributeValue`. In OTEL, the `io.opentelemetry.sdk.trace.data.SpanData#getAttributes()` returns a `Map<io.opentelemetry.api.common.AttributeKey, Object>`.  We therefore have to change the keys and values accordingly
    - change the key from `String` to `AttributeKey`, e.g., `AttributeKey.stringKey("myKey")`
    - change the value from `AttributeValue` to the Object implementation
         ```Java
        // OC code
        Map<String, io.opencensus.trace.AttributeValue> ocAttributes = span.getAttributes().getAttributeMap();
        AttributeValueString ocAttributeValue = ocAttributes.get("myKey")

        // OTEL Code
        Map<io.opentelemetry.api.common.AttributeKey, Object> attributes = span.getAttributes().asMap();
        String otelAttributeValue = otelAttributes.get(AttributeKey.stringKey("myKey"));
   - see also the changes in `TraceSettingsTest#testAttributeWritingToParentSpan`

### Context propagation

OpenCensus and inspectIT Ocelot use `io.grpc.Context` to propagate data, such as the `InspectitContext`, `Span` or `TraceId`. OpenTelemetry uses its own `io.opentelemetry.context.Context` implementation. To make all system tests succeed, we need to concurrently support (re-)storing data in `io.grpc.Context` as well as `io.opentelemetry.context.Context`. As an intermediate solution, we changed the following files to support both implementation of [...]

2022-02-17 10:32 UTC, mariusoe requested changes
> Reviewed 1 of 78 files at r4, 7 of 53 files at r5, 1 of 1 files at r6, 4 of 82 files at r7, 48 of 54 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: 52 of 89 files reviewed, 43 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[THIRD-PARTY-LICENSES.txt, line 2 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtImyoW-y-UTNLTnAkx:-MtImyoW-y-UTNLTnAky:blbij1e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/THIRD-PARTY-LICENSES.txt#L2)):*
> ```help
> 
> Dependency License Report for inspectit-ocelot SNAPSHOT
> ```

Can you regenerate this file in order to include the versions of the newly added libraries.

```
$ gradlew generateLicenseReport
```
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java, line 202 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtImnYr8F5myxk_rlTa:-MtImnYr8F5myxk_rlTb:b3xyfth) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java#L202)):*
> ```Java
>         }
> 
>         return resolvedPath.toString().replaceAll("\\\\", "/");
> ```

Use `replace("\\", "/")` instead. That's simpler imo. :)



_Code quote:_
```Java
replaceAll("\\\\", "/")
```
___
*[inspectit-ocelot-agent/build.gradle, line 114 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDcPjB-QhKwMSustxn:-MtDcPjB-QhKwMSustxo:bk5zt7d) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L114)):*
> ```Gradle
> 
>             // for InMemorySpanExporter
>             platform("io.opentelemetry:opentelemetry-bom:${openTelemetryVersion}"),
> ```

This exists already in the `systemTestCompileOnly` block-



_Code quote:_
```Gradle
platform("io.opentelemetry:opentelemetry-bom:${openTelemetryVersion}"),
```
___
*[inspectit-ocelot-agent/build.gradle, line 229 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDcbyN3hnjvDj5thm-:-MtDcbyN3hnjvDj5thm0:bb713o1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L229)):*
> ```Gradle
>                 jvmArgs "-Dinspectit.config.file-based.path=$projectDir/src/system-test/resources/config"
>                 // make inspectIT scan the workdir for configs
>                 jvmArgs "-Dinspectit.publishOpenTelemetryToBootstrap=true"  // make inspectIT push OC to the bootstrap
> ```

OTel



_Code quote:_
```Gradle
OC
```
___
*[inspectit-ocelot-agent/build.gradle, line 233 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDd8Px9D7Wd9yPjeMP:-MtDd8Px9D7Wd9yPjeMQ:b-3u86s7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L233)):*
> ```Gradle
>                 // JaCoCo agent first + bootstrap instrumentation
>                 jvmArgs "-javaagent:${agentJarPath}"  // Our agent second.
>                 jacoco.enabled = false  // Don't add the JaCoCo agent again.
> ```

Can you move this statement to the end (after the strictContext flag), so that all `jvmArgs=...` are in a single block.



_Code quote:_
```Gradle
jacoco.enabled = false
```
___
*[inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java, line 93 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2EhNr8BmyedcvZNZy:-Mw2EhNr8BmyedcvZNZz:b1p3tzs) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L93)):*
> ```Java
>     }
> 
>     private static void startAgent(String agentArgs, Instrumentation inst, TelemetrySettings telemetrySettings) {
> ```

Method is not used and can be removed.
___
*[inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java, line 136 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2EtUi-DAa60U7sd0u:-Mw2EtUi-DAa60U7sd0v:bwthngd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L136)):*
> ```Java
>      * @throws IOException
>      */
>     private static InspectITClassLoader initializeInspectitLoader(Instrumentation inst, TelemetrySettings telemetrySettings) throws IOException {
> ```

As far as I can see this is not used as well. Why are these methods added?

If not needed, the `TelemetrySettings` class can be removed as well.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java, line 24 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2FOq57w75XH_Uoub1:-Mw2FOq57w75XH_Uoub2:bvhmw0j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java#L24)):*
> ```Java
>     final static InMemorySpanExporter spanExporter = TestUtils.initializeOpenTelemetryForSystemTesting();
> 
>     protected List<io.opentelemetry.sdk.trace.data.SpanData> getExportedSpans() {
> ```

FQN not needed because of import -> `SpanData`



_Code quote:_
```Java
io.opentelemetry.sdk.trace.data.SpanData
```
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java, line 41 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2FVzQ9pDyUqt0Ern9:-Mw2FVzQ9pDyUqt0ErnA:b-tcfawf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java#L41)):*
> ```Java
> 
>         await().atMost(15, TimeUnit.SECONDS).untilAsserted(() -> {
>             Map<String, List<io.opentelemetry.sdk.trace.data.SpanData>> traces = getExportedSpans().stream()
> ```

`SpanData`



_Code quote:_
```Java
io.opentelemetry.sdk.trace.data.SpanData
```
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 322 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2G7W86q2S8PzuGRgz:-Mw2G7W86q2S8PzuGRh-:b91yzeo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L322)):*
> ```Java
>                 .setSampler(Sampler.alwaysOn())
>                 .addSpanProcessor(BatchSpanProcessor.builder(inMemSpanExporter).build())
>                 .addSpanProcessor(SimpleSpanProcessor.create(new LoggingSpanExporter()))
> ```

Not sure whether we need the logging exporter in the tests when we have the in memory exporter for verifying data.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 347 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2GWWD-5KudcMIFEOE:-Mw2GWWD-5KudcMIFEOF:b-65rycu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L347)):*
> ```Java
>             tracerField.set(null, tracer);
> 
>             System.out.println("OTEL_TRACER updated to " + tracer + " (" + openTelemetry.getTracer("io.opentelemetry.opencensusshim") + ")");
> ```

Question: should we use a proper logger in the tests as well or just using sout?
___
*[inspectit-ocelot-config [...]

2022-02-18 07:38 UTC, heiko-holz reviewed
> Reviewed 1 of 82 files at r7, 21 of 54 files at r8, 6 of 27 files at r9.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: 32 of 90 files reviewed, 43 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[THIRD-PARTY-LICENSES.txt, line 2 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtImyoW-y-UTNLTnAkx:-Mw79r4G4vfAYeNxqh2A:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/THIRD-PARTY-LICENSES.txt#L2)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you regenerate this file in order to include the versions of the newly added libraries.

```
$ gradlew generateLicenseReport
```
</blockquote></details>

Done.
___
*[inspectit-ocelot-agent/build.gradle, line 114 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDcPjB-QhKwMSustxn:-Mw6hGM633WB7LsSmY-z:bq3hmmb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L114)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

This exists already in the `systemTestCompileOnly` block-
</blockquote></details>

We still need it in the `systemTestImplementation` block as we are otherwise missing the versions obtained from the `bom`
___
*[inspectit-ocelot-agent/build.gradle, line 229 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDcbyN3hnjvDj5thm-:-Mw6hbzcB48qyQDLtJf2:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L229)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

OTel
</blockquote></details>

Done.
___
*[inspectit-ocelot-agent/build.gradle, line 233 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDd8Px9D7Wd9yPjeMP:-Mw6hlveDNiwlvEMUxvT:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L233)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you move this statement to the end (after the strictContext flag), so that all `jvmArgs=...` are in a single block.
</blockquote></details>

Done.
___
*[inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java, line 93 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2EhNr8BmyedcvZNZy:-Mw6hvMU-3owWtHaISaz:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L93)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Method is not used and can be removed.
</blockquote></details>

Done.
___
*[inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java, line 136 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2EtUi-DAa60U7sd0u:-Mw6i5kG1w8eS62R8Dmx:bq11ldi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L136)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As far as I can see this is not used as well. Why are these methods added?

If not needed, the `TelemetrySettings` class can be removed as well.
</blockquote></details>

Thanks for spotting this!
This was an intermediate implementation where both, OC and OTEL, were supported for testing purposes.

`TelemetrySettings` and `TelemetryImplementation` have been safely deleted.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java, line 24 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2FOq57w75XH_Uoub1:-Mw6iWLsBr3lKaLRXe8E:b-d7ab9g) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java#L24)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

FQN not needed because of import -> `SpanData`
</blockquote></details>

Thanks for spotting this!
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java, line 41 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2FVzQ9pDyUqt0Ern9:-Mw6jj2PDANfBJBNSgEA:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java#L41)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

`SpanData`
</blockquote></details>

Done.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 322 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2G7W86q2S8PzuGRgz:-Mw6jrtw7bAtseiF_696:b-b0imsn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L322)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Not sure whether we need the logging exporter in the tests when we have the in memory exporter for verifying data.
</blockquote></details>

You are right. The `LoggingSpanExporter` was to visually inspect the behavior. I completely removed the `LoggingSpanExporter` from the `build.gradle` in the agent project as well.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 347 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2GWWD-5KudcMIFEOE:-Mw7TjynDXGLdAh_nhjT:b-chadk7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L347)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Question: should we use a proper logger in the tests as well or just using sout?
</blockquote></details>

Good point! I added a `private static final Logger logger = LoggerFactory.getLogger(TestUtils.class);` to `TestUtils.java` for logging purposes and replaced respective `System.out.println` and `System.err.println` calls.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/LoggingMetricsExporterSettings.java, line 23 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw2GeyB7KT2zI3lctmG:-Mw6kmU11iSAg6ldcsG_:bglprsd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/LoggingMetricsExporterSettings.java#L23)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Every millisecond the metrics are pushed? Shouldn't this be more like every 10 or 15 seconds?
</blockquote></details>

This only declares that the **minimum** export interval allowed is 1 ms (I copied this from `InfluxExporterSettings.java`). It defauls to `${inspectit.metrics.frequency}`, which is defaults to 15s according to `system-and-jvm-metrics.yml`.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/PropagationFormat.java, line 24 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw65nxW3xOceJX1NTJL:-Mw7 [...]

2022-02-18 09:21 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: 89 of 90 files reviewed, 6 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java, line 33 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtIpC9S60yL0BFCaWhQ:-MwAznYe6nrQGTwGWLoT:b-aw65fo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java#L33)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

It looks like that you need to mock an OTel span but creating an `io.opencensus.trace.Span` with the `@Mock` annotation. Can you try to use a mock with type `io.opencensus.trace.Span`instead the OpenCensus one?
</blockquote></details>

The problem is that `io.opentelemetry.api.trace.Span` does **not** implement `io.opencensus.trace.Span` (and all our functionality expects `io.opencensus.trace.Span`), but `Tracing.getTracer().getCurrentSpan()` returns an `io.opentelemetry.opencensusshim.OpenTelemetrySpanImpl` or `OpenTelemetryNoRecordEventsSpanImpl` (which extend `io.opencensus.trace.Span`, but these classes are not accessible), and this call is used in the tests`verifyNoAttbiutesWrittenIfNoSpanStarted()` and `verifyAttributesWritten()` as well as in `WriteSpanAttributesAction.java`. When trying to mock for example `io.opentelemetry.opencensusshim.OpenTelemetryNoRecordEventsSpanImpl` via reflection leads to further issues with `io.opencensus.trace.Tracer.withSpan`. I can completely move to OTEL for this test class, but I think opting for a `Spy` instead of a `Mock` is more convenient at the moment. 


<!-- Sent from Reviewable.io -->

2022-02-18 09:36 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: 89 of 90 files reviewed, 6 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md, line 1 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MwAmehJ6eF4qn1JTT7B:-MwBAQsgAfI0Hp3oryke:b-slu7cj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/15ea43e0e0c4703abae8676c1a17224029d66aa1/inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md#L1)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

That's a really nice documentation site :) I like!
</blockquote></details>

Props to the person who created the `open-census-configuration.md` ;)
___
*[inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md, line 13 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MwAmN027PEGan8_uH-_:-MwBAfHU-J5HaA_OnG2e:baqr91) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/15ea43e0e0c4703abae8676c1a17224029d66aa1/inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md#L13)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Do you mean `OpenTelemetry`?
</blockquote></details>

Yes, but let's discuss this how we inform the users that currently both, OTEL and OC are supported using the bridge.


<!-- Sent from Reviewable.io -->

2022-02-28 15:07 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: 85 of 90 files reviewed, 6 unresolved discussions (waiting on @mariusoe)

___
*[inspectit-ocelot-agent/build.gradle, line 114 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtDcPjB-QhKwMSustxn:-Mx-eh5xAs1Z6s0GoL3G:b-nmiylg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/34f63062589487395f08f8bc6b5599f566c8b831/inspectit-ocelot-agent/build.gradle#L114)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's discuss this.
</blockquote></details>

As discussed, we keep the original version (i.e., using `compileOnly`, `implementation`, and `testImplementation`).

We also think that we need to keep the separation due to the bootstrap loading strategy of InspectIT Ocelot.
___
*[inspectit-ocelot-core/build.gradle, line 33 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtIlb-h63YWptOmXrKI:-Mx-f8lbEbbN4k_xGgnR:blh5h3f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-core/build.gradle#L33)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's talk about this once more please.
</blockquote></details>

See the comment to the `build.gradle` file of the `agent` project
___
*[inspectit-ocelot-core/build.gradle, line 102 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtImH5-2xN7qcEgw8XD:-Mx-fIv1BkfB99_lXWn_:b6stg0r) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-core/build.gradle#L102)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As far as I know, `testImplementation`extends the ìmplementation`configuration, thus, you don't need the sdk, ... dependencies here, because they are already in the ìmplemenation`one
</blockquote></details>

The `io.opentelemetry:opentelemetry-sdk` is **not** in the `implementation` scope, but in the `compileOnly` scope. Thus, we also need to include it in the `testImplementation` scope.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/LoggingTraceExporterService.java, line 120 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-Mw67aCf3VeSesEXLVjA:-Mx-oLZR4zruMpVoVotf:b-byfnyx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/LoggingTraceExporterService.java#L120)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Yeah, let's discuss this.
</blockquote></details>

As we are currently not using OTEL's context propagation, we removed the `ContextPropagators` from `LoggingTraceExporterService.java` and `TestUtils.java`
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java, line 33 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MtIpC9S60yL0BFCaWhQ:-Mx-dqhOAhwqsMrZVVle:bbsneg4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/83ddcbed1fb4cda4a35ec988196c75201f1717f7/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java#L33)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

The problem is that `io.opentelemetry.api.trace.Span` does **not** implement `io.opencensus.trace.Span` (and all our functionality expects `io.opencensus.trace.Span`), but `Tracing.getTracer().getCurrentSpan()` returns an `io.opentelemetry.opencensusshim.OpenTelemetrySpanImpl` or `OpenTelemetryNoRecordEventsSpanImpl` (which extend `io.opencensus.trace.Span`, but these classes are not accessible), and this call is used in the tests`verifyNoAttbiutesWrittenIfNoSpanStarted()` and `verifyAttributesWritten()` as well as in `WriteSpanAttributesAction.java`. When trying to mock for example `io.opentelemetry.opencensusshim.OpenTelemetryNoRecordEventsSpanImpl` via reflection leads to further issues with `io.opencensus.trace.Tracer.withSpan`. I can completely move to OTEL for this test class, but I think opting for a `Spy` instead of a `Mock` is more convenient at the moment. 
</blockquote></details>

As discussed, we keep the original implementation with `@Spy Span` for convenience.

As soon as we completely move to OTEL, this becomes obsolete as we will only work with OTEL's implementation. Thus, the `@Spy` can then be changed to `@Mock` again.
___
*[inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md, line 13 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270#-MwAmN027PEGan8_uH-_:-Mx-hn-m5xE2AN99bvDh:b5mwbpt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/15ea43e0e0c4703abae8676c1a17224029d66aa1/inspectit-ocelot-documentation/docs/configuration/open-telemetry-configuration.md#L13)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yes, but let's discuss this how we inform the users that currently both, OTEL and OC are supported using the bridge.
</blockquote></details>

We will finish the configuration documentation with the pull requests that finished the OTEL (bridge) integration.


<!-- Sent from Reviewable.io -->

2022-03-01 10:12 UTC, mariusoe approved these changes
> Reviewed 1 of 1 files at r10, 4 of 4 files at r11, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)



<!-- Sent from Reviewable.io -->

2022-03-01 10:13 UTC, merged