Closes #1289 - Create a component for generating configuration documentations
inspectIT/inspectit-ocelot pull request #1293
Opened 2022-02-02 10:34 UTC by aaronweissler

2022-02-02 12:52 UTC, MariusBrill requested changes
> Reviewed 21 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 15 of 74 files reviewed, 27 unresolved discussions (waiting on @aaronweissler and @MariusBrill)

___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 7 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuUC1W3KbOxcjOXEiD:-MuuUC1W3KbOxcjOXEiE:b-ew65aa) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L7)):*
> ```Java
> import rocks.inspectit.ocelot.config.model.InspectitConfig;
> 
> public class ConfigDocManager {
> ```

I am not quite sure what this class is needed for - let's talk about it.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 35 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuKVt12rX8XzoZI2LO:-MuuKVt29D8dLZ9ETU5y:bkepz8v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L35)):*
> ```Java
> 
>         //Parse the InspectitConfig from the created YAML String
>         ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
> ```

It should be sufficient to instantiate the objectMapper only once in the constructor of the ConfigParser instead of creating a new one with each method call
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 44 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuKxO42DdneZ-KDqO6:-MuuKxO42DdneZ-KDqO7:bw0b0ie) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L44)):*
> ```Java
>         //In the YAML property-names are kebab-case in the Java objects CamelCase, Jackson can do that conversion
>         //with the following line
>         mapper.setPropertyNamingStrategy(PropertyNamingStrategies.KEBAB_CASE);
> ```

Same as with ObjectMapper - just instantiate once in the constructor of this class
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 62 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuMkX2Au4U3keC--vS:-MuuMkX2Au4U3keC--vT:bvvd830) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L62)):*
> ```Java
>      * @return The YAML-String with the placeholders replaced.
>      */
>     protected String replacePlaceholders(String configYaml){
> ```

Is there a reason this method is protected instead of private?
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 65 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuMfpW30eQXN8xwtPJ:-MuuMfpW30eQXN8xwtPK:bbv9q32) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L65)):*
> ```Java
> 
>         //deserialize YAML to Map to get the placeholders' values from
>         ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
> ```

See ObjectMapper comment above
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuNWO993vwofhuSuwx:-MuuNWO993vwofhuSuwy:b-k1b64y) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L71)):*
> ```Java
>             //find the first occurence of the ${placeholder} syntax
>             int index = configYaml.indexOf("${");
>             while (index >= 0) {
> ```

I think you could make this whole method easier by using the StringSubstitutor: https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuNd3-3dvzYhxXV2yW:-MuuNd3-3dvzYhxXV2yX:bkzcfpu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L90)):*
> ```Java
>                 index = configYaml.indexOf("${");
>             }
>         } catch (IOException e) {
> ```

If you just print out StackTraces you can also just add a throws-declaration to the method instead of catching the Exception and printing it.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 103 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuONQc2AlJJyo1biYG:-MuuONQc2AlJJyo1biYH:b13ysx5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L103)):*
> ```Java
>      * @return The value from within the nested Maps.
>      */
>     private String getNestedValue(Map<String, Object> map, List<String> keys) {
> ```

Should be obsolete if you use the StringSubstitutor. If not we should have a chat on what excactly this method does.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java, line 139 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuOwjSEY2ynEC5jpNh:-MuuOwjT1MRLaMEozO8U:b-92rkbg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigParser.java#L139)):*
> ```Java
>      * @return Returns the corresponding Duration object.
>      */
>     private static Duration parseHuman(String text) {
> ```

Lets talk about this method. I think it can be simplified using something like SimpleDateFormat
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 10 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuQKJY6E9JOlTckGZJ:-MuuQKJY6E9JOlTckGZK:b-wkbsnu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java#L10)):*
> ```Java
> public class ActionDoc extends BaseDoc {
> 
>     public ActionDoc(String name, String description, List<ActionInputDoc> inputs, String returnDescription, Boolean isVoid) {
> ```

Lombok should automatically generate constructors with the @Data-annotation so no need to write them yourself.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-o [...]

2022-02-03 15:28 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 1 of 77 files reviewed, 27 unresolved discussions (waiting on @aaronweissler and @MariusBrill)

___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 7 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuUC1W3KbOxcjOXEiD:-Muy_LYyBnhkXYnSBeTh:b-q0hbot) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L7)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I am not quite sure what this class is needed for - let's talk about it.
</blockquote></details>

Done.
Discussion result: Keep for now but talk about it again with next related PR.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 10 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuQKJY6E9JOlTckGZJ:-MuyfefS8vRXKfPZeNRj:bc442vd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java#L10)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Lombok should automatically generate constructors with the @Data-annotation so no need to write them yourself.
</blockquote></details>

Unfortunately, Lombok's constructor generation apparently does not play nice with inheritance, because it would only call the super-class's base constructor without any arguments and also only generate a constructor for the child-class with its own fields and not include the super-class's fields. 
See for example: https://stackoverflow.com/questions/29740078/how-to-call-super-constructor-in-lombok/29771875
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuPFcT5I_ia8occOkx:-Muyh4XYAhmX9ibIT7yJ:b-f1uwl4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java#L17)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Is there a reason these variables are package-private?
</blockquote></details>

No, I think I just forgot to change the default.
Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionInputDoc.java, line 8 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuQHnNCMIFbyYYeYqn:-MuykU98Cdr0oFDZmO07:b-awrvw2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionInputDoc.java#L8)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Lombok should automatically generate constructors with the @Data-annotation so no need to write them yourself.
</blockquote></details>

Done.
See comment regarding Lombok and inheritance above.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionInputDoc.java, line 14 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuPKZe7RJUR1kF1Ids:-MuykWnR9KaZSf8zRfzF:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionInputDoc.java#L14)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

See ActionDoc
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java, line 13 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuPOi-Dm9b8mH4Ufah:-MuykXEV1Y-OPRSpVo1d:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java#L13)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

See ActionDoc
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ConfigDocumentation.java, line 10 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuPot3BgOadg3Uh06C:-MuykYxy9l1sF60P-8BS:b-2d4tw5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ConfigDocumentation.java#L10)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Lombok should automatically generate constructors with the @Data-annotation so no need to write them yourself.
</blockquote></details>

Done.
Here I actually can use it, since it doesn't involve inheritance.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java, line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuRxB45TYm-Ylq8BBN:-Mv-9IRR2BNtEI5gA-hb:bcfx02) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java#L58)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Let's talk about these generate-methods. I think there could be a way to generify them.
</blockquote></details>

I can't really find a way to generify them nicely, because I think I'd need a superclass for all of them that has the method getDoc(), but introducing inheritance for them just for saving the about seven lines that are the same in three of the methods, doesn't seem worth it (also considering how that might behave with Lombok as discovered earlier).
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/MetricDoc.java, line 6 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuSMAIAhheJAh-_bj4:-Mv--IGm7j_7DfrIJuyK:b-awrvw2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/MetricDoc.java#L6)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I think you can also use the Data-Annotation here
</blockquote></details>

Done.
See comment regarding Lombok and inheritance above.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/MetricDoc.java, line 13 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuSETcBE30oxncM4sm:-MuyktMe6RP2r2dUAF3X:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/gener [...]

2022-02-07 11:05 UTC, MariusBrill requested changes
> Reviewed 45 of 54 files at r2, 13 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 59 of 77 files reviewed, 17 unresolved discussions (waiting on @aaronweissler and @MariusBrill)

___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ScopeDoc.java, line 3 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIDo67Ad3zgHDPtLR7:-MvIDo67Ad3zgHDPtLR8:b-793c83) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ScopeDoc.java#L3)):*
> ```Java
> package inspectit.ocelot.config.doc.generator.docobjects;
> 
> public class ScopeDoc extends BaseDoc {
> ```

I guess you added this white space by mistake?
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 19 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIEnOh8X25S4Z0fbsg:-MvIEnOi4BrwWjRfsZ5T:bwpg9su) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L19)):*
> ```Java
> 
> @Slf4j
> public class ConfigParser {
> ```

Also add a small documentation on what this class is used for
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 34 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIEkpQ-FrBFMR1yZ16:-MvIEkpQ-FrBFMR1yZ17:b5v1oij) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L34)):*
> ```Java
>     }
> 
>     ObjectMapper mapper;
> ```

Can be private
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 66 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIFApBDpeycnyU1AOD:-MvIFApBDpeycnyU1AOE:b2mhqyy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L66)):*
> ```Java
>      * @return Returns the corresponding Duration object.
>      */
>     private static Duration parseHuman(String text) {
> ```

I think this method belongs to CustomDurationDeserializer
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java, line 109 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIMT9x64LL8F6VBMO8:-MvIMT9y3gJYsPxmBASC:b-pagats) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java#L109)):*
> ```Java
>     }
> 
>     ConfigDocManager configDocManager = new ConfigDocManager();
> ```

Just use  @InjectMocks
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java, line 166 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvILOsoB4xeu8L7oI5x:-MvILOsoB4xeu8L7oI5y:b-c3vm36) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java#L166)):*
> ```Java
>             ConfigDocumentation expected = new ConfigDocumentation(Collections.emptyList(), actions,
>                     Collections.emptyList(), Collections.emptyList());
>             assertEquals(expected, result);
> ```

Instead of using one assertEquals statement create one for each variable in ConfigDocumentation - this way we can find errors easier as you can see which assertion fails.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java, line 31 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIOkuD8xPy7ZhODwxU:-MvIOkuD8xPy7ZhODwxV:brolvne) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java#L31)):*
> ```Java
> class ConfigParserTest {
> 
>     private final ConfigParser configParser = new ConfigParser();
> ```

Use  @InjectMocks
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java, line 58 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIOnT00OgwtLX0YCWZ:-MvIOnT00OgwtLX0YCW_:b-ti9j7l) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java#L58)):*
> ```Java
>                     variable1, variable2, variable3, variable4);
> 
>             ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
> ```

Instead of using an instance of ObjectMapper you can just mock the class as we don't want to test it in the unit test.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java, line 107 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIP3et22Zr2Qq9WSny:-MvIP3et22Zr2Qq9WSnz:bitk7o) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java#L107)):*
> ```Java
>             pollingSettings.setEnabled(enabledMap);
> 
>             MetricDefinitionSettings metricDefinition = MetricDefinitionSettings.builder()
> ```

Just use mocks instead of instances of the Settings-Objects
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java, line 193 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIPEkgCqs8bxyocY0U:-MvIPEkgCqs8bxyocY0V:b-cv7w4s) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java#L193)):*
> ```Java
>             actions.put("a_debug_println", action);
> 
>             InstrumentationSettings instrumentation = new InstrumentationSettings();
> ```

Again - just use mocks
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/docobjects/RuleDocTest.java, line 124 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIdLC9CVFQHZlBBNNR:-MvIdLC9CVFQHZlBBNNS:b38n3pd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/docobjects/RuleDocTest.java#L124)):*
> ```Java
>             RuleActionCallDoc overwritten_by_2 = expected.get(RULE_2_NAME).getEntryExits().get(ENTRY_KEY).get(OVERWRITTEN_BY_2);
>             RuleActionCallDoc inherited_from_2 = new RuleActionCallDoc(overwritten_by_2, RULE_2_NAME);
>             expected.get(RULE_1_NAME).getEntryExits().get(ENTRY_KEY).put(OVERWRITTEN_BY_2, inherited_from_2);
> ```

Just use mocks
___
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/regex.yml, line 230 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1 [...]

2022-02-09 13:59 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 50 of 77 files reviewed, 17 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java, line 36 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuQwpN9P824qE_ABkd:-MvP1Zzn3L3cvjR9wYkQ:b-nhvwyo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java#L36)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Let's talk about the structure of this method - I think we can refactore it to increase readability
</blockquote></details>

Done.
See comment below
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java, line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MuuRxB45TYm-Ylq8BBN:-MvP1b-12RzqGz8VsL4H:b8xjhqh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/857cd9edcb1b036d28e7728b17d97547dacbc3d6/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java#L58)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

I can't really find a way to generify them nicely, because I think I'd need a superclass for all of them that has the method getDoc(), but introducing inheritance for them just for saving the about seven lines that are the same in three of the methods, doesn't seem worth it (also considering how that might behave with Lombok as discovered earlier).
</blockquote></details>

Done.
Talked about it, not possible with the current architecture.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ScopeDoc.java, line 3 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIDo67Ad3zgHDPtLR7:-MvJZ7KV-WeOk8vDEqZy:btnjcnt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ScopeDoc.java#L3)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I guess you added this white space by mistake?
</blockquote></details>

Didn't the most recent change remove it, or did I add it accidentally when force pushing the oldercommit with some changes? 
But yes, it probably came from some annotation that I removed before and forgot to remove the full line as well.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/docobjects/RuleDocTest.java, line 124 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIdLC9CVFQHZlBBNNR:-MvTYHWv6At80MoPS9tY:bb6un1j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/docobjects/RuleDocTest.java#L124)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Just use mocks
</blockquote></details>

Done
___
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/regex.yml, line 230 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIe6BO-GwCm9w7dtZB:-MvK8RDz9zu0QYVDdXVW:bfqj589) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/955c5b3ca226c0bbfe903321c7b19af10774fed8/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/regex.yml#L230)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Ist there a reason you removed this config?
</blockquote></details>

Done
I mean, yes, I removed it on purpose while debugging, but no, of course it was not supposed to stay in the commit ^^
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 19 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIEnOh8X25S4Z0fbsg:-MvJ_YI00PD4yGd2CCyq:bb6un1j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L19)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Also add a small documentation on what this class is used for
</blockquote></details>

Done
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 34 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIEkpQ-FrBFMR1yZ16:-MvJZdSV4_5B_euEmDzV:bb6un1j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L34)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Can be private
</blockquote></details>

Done
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java, line 66 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIFApBDpeycnyU1AOD:-MvJ_ZtX7PjqxjGgH-F2:beuvbag) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/main/java/parsing/ConfigParser.java#L66)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I think this method belongs to CustomDurationDeserializer
</blockquote></details>

Done
Yeah, makes more sense to just put it in there.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java, line 109 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvIMT9x64LL8F6VBMO8:-MvTZToz-DgIY6hBndDN:b-h0f8gj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java#L109)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Just use  @InjectMocks
</blockquote></details>

This file was refactored, so this specific line isn't in it anymore anyways, but for the analogous line, the same is the case as within ConfigParserTest, it wouldn't create any object, because there are no mocks to inject.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java, line 166 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-MvILOsoB4xeu8L7oI5x:-MvJaCYR85t6ooShBnlu:b43xqi9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9c93058b0815f208b15602a093d06c557cef6ae8/components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigDocManagerTest.java#L166)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Instead of using one assertEquals statement create one for each variable in ConfigDocumentation - this way we can find errors easier as you can see which assertion fails.
</blockquote></details>

Done.
Actually using assertj's usingRecursiveComparison instead now.
___
*[components/inspectit-ocelot-config-doc-generator/src/test/java/inspectit/ocelot/config/doc/generator/ConfigParserTest.java, line 31 at [...]

2022-02-16 11:18 UTC, mariusoe requested changes
> Reviewed 1 of 73 files at r1, 4 of 54 files at r2, 5 of 29 files at r4, 9 of 14 files at r6, 2 of 2 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 59 of 77 files reviewed, 39 unresolved discussions (waiting on @aaronweissler and @MariusBrill)

___
*[settings.gradle, line 13 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1CBxP1Qz85eWBdi9w:-Mw1CBxP1Qz85eWBdi9x:b-m72ub3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/settings.gradle#L13)):*
> ```Gradle
> project(':inspectit-ocelot-configurationserver').projectDir = new File('./components/inspectit-ocelot-configurationserver')
> project(':inspectit-ocelot-eum-server').projectDir = new File('./components/inspectit-ocelot-eum-server')
> project(':inspectit-ocelot-config-doc-generator').projectDir = new File('./components/inspectit-ocelot-config-doc-generator')
> ```

How about naming this project: `inspecit-ocelot-configdocsgenerator` or `inspecit-ocelot-docsgenerator`?



_Code quote:_
```Gradle
inspectit-ocelot-config-doc-generator
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 1 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0kTC8DTPlNBuzsQ2O:-Mw0kTC8DTPlNBuzsQ2P:bsv7vqh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L1)):*
> ```Java
> package inspectit.ocelot.config.doc.generator;
> ```

Please use the package name `inspectit.ocelot.docsgenerator`



_Code quote:_
```Java
inspectit.ocelot.config.doc.generator
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 1 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0kd7iEfjM2VstNmCT:-Mw0kd7iEfjM2VstNmCU:b-tg5703) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L1)):*
> ```Java
> package inspectit.ocelot.config.doc.generator;
> ```

Please use in the naming (and in the model `docs`instead of `doc`). Imo, `docs` is more likely to be associated with documentation than `doc`.



_Code quote:_
```Java
doc
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 8 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0k6bnDszJ0FGzqPFL:-Mw0k6bnDszJ0FGzqPFM:b-l3ii1v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L8)):*
> ```Java
> import rocks.inspectit.ocelot.config.model.InspectitConfig;
> 
> public class ConfigDocManager {
> ```

It's more like a `Generator` instead of a `Manager`



_Code quote:_
```Java
ConfigDocManager
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 18 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1A-W03EWTgoE1rNcg:-Mw1A-W03EWTgoE1rNch:bpox2dp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java#L18)):*
> ```Java
>     }
> 
>     private final List<ActionInputDoc> inputs;
> ```

Fields should be located above the constructor.
Please use this ordering in all classes.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java, line 8 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0nrSQCJN1FPFV15kb:-Mw0nrSQCJN1FPFV15kc:b7c9nlz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java#L8)):*
> ```Java
> @RequiredArgsConstructor
> @Getter
> public abstract class BaseDoc {
> ```

Please move all "data" classes into a separate package, e.g.: `..generator.model`
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java, line 10 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0o4EA0NkRUssdj9KE:-Mw0o4EA0NkRUssdj9KF:b-bw31ga) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java#L10)):*
> ```Java
> public abstract class BaseDoc {
> 
>     private final String name;
> ```

Please format all files with the ocelot code style: https://github.com/inspectIT/inspectit-ocelot/blob/master/codequality/idea/code_style.xml
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java, line 27 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1ACQ6Ed0fU2hcF6Uv:-Mw1ACQ6Ed0fU2hcF6Uw:bbeda7h) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java#L27)):*
> ```Java
> public class DocObjectGenerator {
>     
>     public ConfigDocumentation generateConfigDocumentation(InspectitConfig config){
> ```

Please add documentation to the public methods and classes (what are they doing and what are the arguments for).
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java, line 19 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1B-GJ7fN4x4eijxKU:-Mw1B-GJ7fN4x4eijxKV:b-f9asjm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java#L19)):*
> ```Java
>     }
> 
>     private final String name;
> ```

`ruleName`



_Code quote:_
```Java
name
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java, line 20 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1B1DC0pvD0-KcaHuy:-Mw1B1DC0pvD0-KcaHuz:b-odmam4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java#L20)):*
> ```Java
> 
>     private final String name;
>     private final String action;
> ```

`actionName`



_Code quote:_
```Java
action
```
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java, line 21 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1B47XABRuXXfRJwl8:-Mw1B47XABRuXXfRJwl9:b-tgq5n0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java#L21)):*
> ```Java
>     private final String name;
>     private final String action;
>     pr [...]

2022-02-17 10:45 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 1 of 89 files reviewed, 39 unresolved discussions (waiting on @MariusBrill and @mariusoe)

___
*[settings.gradle, line 13 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1CBxP1Qz85eWBdi9w:-Mw1d05I5RxcWqnE6hP1:b-w56b91) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/settings.gradle#L13)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

How about naming this project: `inspecit-ocelot-configdocsgenerator` or `inspecit-ocelot-docsgenerator`?
</blockquote></details>

Done.
Renamed to inspectit-ocelot-configdocsgenerator
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/actions/GenericActionSettings.java, line 55 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1EEUk9IyJpyTLaNtu:-Mw1ybgL07PO4U11ch_c:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/actions/GenericActionSettings.java#L55)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Javadocs should end with a dot `.`
</blockquote></details>

Done.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/actions/GenericActionSettings.java, line 57 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1EBRx5ZussDQSR0Zx:-Mw1a-OyCHw5zn8Rj9NF:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/actions/GenericActionSettings.java#L57)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please use `docs`. Same for scopes and rules.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 1 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0kTC8DTPlNBuzsQ2O:-Mw1d23G5rysKhmJ91Vv:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L1)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please use the package name `inspectit.ocelot.docsgenerator`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 1 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0kd7iEfjM2VstNmCT:-Mw1d9J898jtEtVblSH0:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L1)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please use in the naming (and in the model `docs`instead of `doc`). Imo, `docs` is more likely to be associated with documentation than `doc`.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java, line 8 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0k6bnDszJ0FGzqPFL:-Mw1y-mg479I0-TTYGtg:b-n7sg10) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/ConfigDocManager.java#L8)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

It's more like a `Generator` instead of a `Manager`
</blockquote></details>

Done.
Actually also refactored this to combine this class and the DocObjectGenerator.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java, line 18 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1A-W03EWTgoE1rNcg:-Mw1TT2o9Xq4ai0ppc-A:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/ActionDoc.java#L18)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Fields should be located above the constructor.
Please use this ordering in all classes.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java, line 8 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0nrSQCJN1FPFV15kb:-Mw1y88w-1gQJDFRiCsw:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java#L8)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please move all "data" classes into a separate package, e.g.: `..generator.model`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java, line 10 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw0o4EA0NkRUssdj9KE:-Mw1KEZX6wMJs4M0TGDr:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/BaseDoc.java#L10)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please format all files with the ocelot code style: https://github.com/inspectIT/inspectit-ocelot/blob/master/codequality/idea/code_style.xml
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java, line 27 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1ACQ6Ed0fU2hcF6Uv:-Mw6Gg-R5lZJjehd0McR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/DocObjectGenerator.java#L27)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please add documentation to the public methods and classes (what are they doing and what are the arguments for).
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java, line 19 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw1B-GJ7fN4x4eijxKU:-Mw1yFLtDih8a9YBKHAt:b-qm1z2n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c0a7b14346d35791d7a4b6df1dbac714608e0d94/components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/generator/docobjects/RuleActionCallDoc.java#L19)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

`ruleName`
</blockquote></details>

Done.
Discussed it, name is correct. Added JavaDoc to make it more understandable.
___
*[components/inspectit-ocelot-config-doc-generator/src/main/java/inspectit/ocelot/config/doc/g [...]

2022-02-17 11:12 UTC, mariusoe requested changes
> Reviewed 18 of 76 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: 18 of 89 files reviewed, 41 unresolved discussions (waiting on @aaronweissler, @MariusBrill, and @mariusoe)

___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/ConfigDocsGenerator.java, line 30 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6N1tJ0wMYb9FnJB_9:-Mw6N1tJ0wMYb9FnJB_A:b-4ro6u8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/ConfigDocsGenerator.java#L30)):*
> ```Java
>  */
> public class ConfigDocsGenerator {
> ```

As far as I see, there is no reason why you should create multiple instances of this class. You just want to use the `generate..` method.
In order to rpevent unneccessary object creating, we can use a singleton pattern here.

Just create one instance, that will be used everywhere.

```
 public static final ConfigDocsGenerator INSTANCE = new ConfigDocsGenerator();
    
 private ConfigDocsGenerator() {
 }
```

or

```
private static final ConfigDocsGenerator INSTANCE = new ConfigDocsGenerator();

public static ConfigDocsGenerator getInstance() {
    return INSTANCE;
}

private ConfigDocsGenerator() {
}
```
___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/MetricDocs.java, line 18 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6KoUsA13nYoWnY4tp:-Mw6KoUsA13nYoWnY4tq:b-xmhhda) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/MetricDocs.java#L18)):*
> ```Java
> 
>     public MetricDocs(String name, String description, String unit) {
> ```

Remove the empty line please :)
___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/MetricDocs.java, line 20 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6Kk6n9h50atN_YjVI:-Mw6Kk6o-3a3sEieqiCR:bnnn2fk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/MetricDocs.java#L20)):*
> ```Java
> 
>         // MetricDefinitions do not contain the info for the since field, so it is left empty
>         super(name, description, "");
> ```

Imo `null` is better to represent that it does not exists.



_Code quote:_
```Java
""
```
___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/RuleDocs.java, line 99 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6LQLQ8_NiYmzGyNQ5:-Mw6LQLQ8_NiYmzGyNQ6:b-why29b) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/RuleDocs.java#L99)):*
> ```Java
>     @Getter
>     @RequiredArgsConstructor
>     public enum EntryExitKey {
> ```

You can move this into a own file because it is used in multiple classes.
___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/RuleDocs.java, line 99 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6LUXT9yuYutrtGwjW:-Mw6LUXT9yuYutrtGwjX:b-rf8xfd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/model/RuleDocs.java#L99)):*
> ```Java
>     @Getter
>     @RequiredArgsConstructor
>     public enum EntryExitKey {
> ```

How about naming it `RuleLifecycleState`? :) More fancy and actually it represents the state of the rule. What do you think?



_Code quote:_
```Java
EntryExitKey
```
___
*[components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/parsing/StringSubstitutorNestedMap.java, line 13 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293#-Mw6MLBu3znaS-NxXUjx:-Mw6MLBu3znaS-NxXUjy:b-b4yn0e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/31b197a7468652f7d3d523346b0ef953083fc311/components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/parsing/StringSubstitutorNestedMap.java#L13)):*
> ```Java
>  * Version of {@link StringSubstitutor} with the possibility to use a nested Map to define values for the replaced variables.
>  */
> public class StringSubstitutorNestedMap extends StringSubstitutor implements StringLookup {
> ```

How about `MapStringSubsitutor`? It's a bit simpler :) 



_Code quote:_
```Java
StringSubstitutorNestedMap
```


<!-- Sent from Reviewable.io -->

2022-02-23 07:59 UTC, mariusoe approved these changes

2022-02-23 08:00 UTC, mariusoe approved these changes
> Reviewed 1 of 1 files at r3, 11 of 29 files at r4, 54 of 76 files at r10, 1 of 1 files at r11, 7 of 9 files at r12, 14 of 14 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1293)* status: all files reviewed, 17 unresolved discussions (waiting on @MariusBrill)



<!-- Sent from Reviewable.io -->

2022-02-23 08:00 UTC, merged