Closes #1248 - Disable all exporters by default
inspectIT/inspectit-ocelot pull request #1303
Opened 2022-02-14 15:32 UTC by aaronweissler

2022-02-14 15:43 UTC, aaronweissler commented
There is one main question for me still left with this, whether and if so how the `enabled` flag should actually be refactored? Because I noticed it has actually always already done what was asked for in the issue's comment: "The exporter will only be started when this flag is true AND when all necessary parameters have been configured."

To me personally the name `enabled` actually is a bit more fitting than `enabledIfConfigured`, since as we talked about not every exporter needs to be configured and I'd find that name confusing for them while to me `enabled` for the ones needing additional configuration seems fine with the newly added warnings.

But of course I'm looking forward to any differing opinions too.

2022-02-14 15:58 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 0 of 16 files reviewed, 10 unresolved discussions

___
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml, line 32 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsu2Iu0tw4BOoJU9_m:-Mvsu2Iu0tw4BOoJU9_n:b-9xw6ae) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml#L32)):*
> ```YAML
>         # the export interval of the metrics
>         export-interval: ${inspectit.metrics.frequency}
> ```

I added these simply for the influx part to be more in line with the others
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java, line 46 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MvsuHv46sHexEB_NHmn:-MvsuHv46sHexEB_NHmo:b7c9ibg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java#L46)):*
> ```Java
>     @Override
>     protected boolean checkEnabledForConfig(InspectitConfig conf) {
>         InfluxExporterSettings influx = conf.getExporters().getMetrics().getInflux();
> ```

I removed two of the statements in the if-statement because as far as I understand neither of database and retentionPolicy can be empty anyways, since they are both annotated with @NotBlank in InfluxExporterSettings.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java, line 47 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsuf27AYzVWaV9SIzV:-Mvsuf285JnPeSlfWefP:bfpsus7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java#L47)):*
> ```Java
>     protected boolean checkEnabledForConfig(InspectitConfig conf) {
>         InfluxExporterSettings influx = conf.getExporters().getMetrics().getInflux();
>         if(conf.getMetrics().isEnabled() && influx.isEnabled()){
> ```

!isEmpty was replaced with hasText because isEmpty has been deprecated.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java, line 5 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsup043OdYAe8HRzqI:-Mvsup043OdYAe8HRzqJ:brf96z3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java#L5)):*
> ```Java
> import io.opencensus.exporter.trace.jaeger.JaegerExporterConfiguration;
> import io.opencensus.exporter.trace.jaeger.JaegerTraceExporter;
> import lombok.extern.slf4j.Slf4j;
> ```

Some of the ExporterServices were using StringUtils from apache.commons.lang3 while others were using a more recent version from spring, so I updated the former to the latter as well.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/InvalidConfigurationUpdateTest.java, line 21 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsv38j3Yy7aGf2eKYE:-Mvsv38j3Yy7aGf2eKYF:b-2zf29r) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/InvalidConfigurationUpdateTest.java#L21)):*
> ```Java
>             mp.setProperty("inspectit.service-name", "ConfA");
>         });
>         Assertions.assertThat(env.getCurrentConfig().getServiceName()).isEqualTo("ConfA");
> ```

The newly created warnings would make this test fail, since none of the exporters get their necessary values set in this test but are enabled by default.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java, line 59 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MvsvW5D82GkSBsLqGT0:-MvsvW5D82GkSBsLqGT1:bmzkxiz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java#L59)):*
> ```Java
>     //@Test This test is currently deactivated, since the current implementation of the trace exporter tries to connect to a google service before starting
>     // and the request runs into a timeout.
>     public void testGrpcRequest() {
> ```

I moved these properties into the test case, since they are only needed there as of now, and the new test would not work with them in @TestPropertySource, because the OpenCensus Metrics Exporter can not be restarted when its properties change, so the warning would never be triggered.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/PrometheusExporterServiceIntTest.java, line 19 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsvsxq7jcFd4g-23pk:-Mvsvsxq7jcFd4g-23pl:b-2yycqh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/PrometheusExporterServiceIntTest.java#L19)):*
> ```Java
> import static org.assertj.core.api.Assertions.assertThat;
> import static org.assertj.core.api.Assertions.catchThrowable;
> ```

Added because the tests expect the Prometheus Exporter to be activated.
___
*[inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md, line 5 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsw6FE4v8PqMhLP0Ot:-Mvsw6FE4v8PqMhLP0Ou:b-u4izr5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md#L5)):*
> ```Markdown
> title: Breaking Changes
> ---
> ```

I am not sure whether this text actually expresses everything properly, but I noticed Marius mentioning it was a breaking change, so I thought I'd try to add it already, so it won't be forgotten.
___
*[inspectit-ocelot-documentation/docs/metrics/metric-exporters.md, line 41 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvswsbi0cNFBWG_ReKb:-Mvswsbi0cNFBWG_ReKc:bhgnsdi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-documentation/docs/metrics/metric-exporters.md#L41)):*
> ```Markdown
> 
> Metrics can be additionally exported to the [OpenCensus Agent](https://opencensus.io/service/components/agent/).
> When enabled, all metrics are sent via gRCP to the OpenCensus Agent. By default, the exporter is enabled, but the agent address that is needed for the exporter to actually start is set to `null`.
> ```

I guess to most people it would be obvious but I felt like it was a good idea to express it a bit more clearly that the exporter won't start without setting the url.
___
*[inspectit-ocelot-documentation/docs/tracing/trace-exporters.md, line 16 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MvswV-pA-sGFPs9FKCv:-MvswV-pA-sGFPs9FKCw:b-7oinw4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e80d2754b66ece99d4af92c9099e5e75b60d63b5/inspectit-ocelot-documentation/docs/tracing/trace-exporters.md#L16)):*
> ```Markdown
> ## Zipkin Exporter
> 
> The Zipkin exporter exports Traces in Zipkin v2 format to a Zipkin server or other compatible servers.
> ```

Zipkin and Jaeger exporters' documentation was not structured like others with an easily overviewable table, I felt like it was a good idea to change that too when already updating some of the docs regarding exporters.
 [...]

2022-02-28 15:39 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 0 of 24 files reviewed, 9 unresolved discussions

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/InvalidConfigurationUpdateTest.java, line 21 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsv38j3Yy7aGf2eKYE:-Mx-yzUX0Cdnm4NKdG0E:b-4olksp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/InvalidConfigurationUpdateTest.java#L21)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

The newly created warnings would make this test fail, since none of the exporters get their necessary values set in this test but are enabled by default.
</blockquote></details>

Could be reverted again due to the now default IF_CONFIGURED not triggering any warnings.


<!-- Sent from Reviewable.io -->

2022-03-01 15:45 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 0 of 32 files reviewed, 10 unresolved discussions

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java, line 54 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx58Olw3tH8ICiNgnah:-Mx58Olw3tH8ICiNgnai:bffdl9i) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/40106210293efba27d5bcb97cf6db566df1f6d77/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java#L54)):*
> ```Java
>             log.info("Starting Jaeger Exporter on grpc '{}'", jaegerExporterSettings.getGrpc());
>         }
> ```

I removed those lines, because they are unreachable due to the `Conditional` annotations.


<!-- Sent from Reviewable.io -->

2022-03-02 07:26 UTC, heiko-holz requested changes
I think we have a nice solution now with using `enum` instead of a single `Boolean`.

Thanks for your great refactoring job!

> Reviewed 4 of 23 files at r2, 27 of 28 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> Dismissed @aaronweissler from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-:-Mx8Uw-e8kCyuNPi-lpD:b8gjx8i)* status: all files reviewed, 15 unresolved discussions (waiting on @aaronweissler)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java, line 49 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5Sk-E6FgT270Bwze6:-Mx5Sk-E6FgT270Bwze7:b-ctshtq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/40106210293efba27d5bcb97cf6db566df1f6d77/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java#L49)):*
> ```Java
>         return influx.isEnabled()
>                 && !StringUtils.isEmpty(influx.getUrl())
>                 && !StringUtils.isEmpty(influx.getDatabase())
> ```

same discussion with `getDatabase()` as for the `inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java`
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java, line 46 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx8U_-f1KmPcVZ5s137:-Mx8U_-f1KmPcVZ5s138:b-7dcu2v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4f31dde829433edf287cf0a0c6d1d18bdbf65c85/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java#L46)):*
> ```Java
>     @ConditionalOnProperty({"inspectit-eum-server.exporters.tracing.jaeger.enabled", "inspectit-eum-server.exporters.tracing.jaeger.grpc"})
>     @ConditionalOnExpression("NOT new String('${inspectit-eum-server.exporters.tracing.jaeger.enabled}').equals('DISABLED') AND new String('${inspectit-eum-server.exporters.tracing.jaeger.grpc}').length() > 0")
>     public SpanExporter jaegerSpanExporter() {
> ```

Would it make sense to have a test class for `TraceExportersConfiguration.java` and test the conditions for `public SpanExporter jaegerSpanExporter()`?
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/BooleanToExporterEnabledStateConverter.java, line 9 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5TvxH8y9L2QD48w6Y:-Mx5TvxH8y9L2QD48w6Z:b-qvuy4p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/284a5fc664a84384de64c72ee719ccb2d3334bec/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/BooleanToExporterEnabledStateConverter.java#L9)):*
> ```Java
> @Slf4j
> @Deprecated
> public class BooleanToExporterEnabledStateConverter implements Converter<Boolean, ExporterEnabledState> {
> ```

Could you add a short comment why this class was originally used and is now deprecated?
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/PrometheusExporterSettings.java, line 32 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5NmBECo0GdI1ZI92y:-Mx5NmBECo0GdI1ZI92z:brhhiyp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/PrometheusExporterSettings.java#L32)):*
> ```Java
>      * The port on which the /metrics endpoint of prometheus will be started.
>      */
>     @Min(1)
> ```

Why did you change this to `@Min(1)`?
___
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml, line 32 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsu2Iu0tw4BOoJU9_m:-Mx8Up4W1ZoibDmb2LE8:b-x869vr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml#L32)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

I added these simply for the influx part to be more in line with the others
</blockquote></details>

I agree, consistency is good. 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java, line 46 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MvsuHv46sHexEB_NHmn:-Mx5Owkt6XlC6Gu9HuSs:b7cfcpd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java#L46)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

I removed two of the statements in the if-statement because as far as I understand neither of database and retentionPolicy can be empty anyways, since they are both annotated with @NotBlank in InfluxExporterSettings.
</blockquote></details>

does this mean that the deserialization of the configuration will throw exceptions if these fields are not set?
We can talk in tomorrow's standup briefly whether we want to explicitly log warnings for all fields that should be set but are not set if `ENABLED` is set.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java, line 5 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsup043OdYAe8HRzqI:-Mx5UGl_E1lkGHBUXbP1:bosamys) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java#L5)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Some of the ExporterServices were using StringUtils from apache.commons.lang3 while others were using a more recent version from spring, so I updated the former to the latter as well.
</blockquote></details>

Just for understanding: we use `org.springframework.util.StringUtils` in favor of `org.apache.commons.lang3.StringUtils` because the former is more recent?
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceIntTest.java, line 75 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5QA-Y1KISx5DvaPxe:-Mx5QA-Y1KISx5DvaPxf:bky9yy6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceIntTest.java#L75)):*
> ```Java
>         });
>         assertLogsOfLevelOrGreater(Level.WARN);
>         assertLogCount("Jaeger Exporter is enabled but no url set.", 1);
> ```

see comment for inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java, line 142 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5Qqf50rkh_3v3LUDc:-Mx5Qqf50rkh_3v3LUDd:bky9yy6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/284a5fc664a84384de64c72ee719ccb2d3334bec/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java#L142)):*
> ```Java
>         });
>         assertLogsOfLevelOrGreater(Level.WARN);
>         assertLogCount("OpenCensus Metrics Exporter is enabled but no address set.", 1);
> ```

see comment for inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/o [...]

2022-03-02 12:27 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 12 of 35 files reviewed, 12 unresolved discussions (waiting on @aaronweissler, @heiko-holz, and @notblank)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java, line 49 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5Sk-E6FgT270Bwze6:-Mx9TeeL8YFtVVHxBE0i:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/40106210293efba27d5bcb97cf6db566df1f6d77/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java#L49)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

same discussion with `getDatabase()` as for the `inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java`
</blockquote></details>

Done.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/BooleanToExporterEnabledStateConverter.java, line 9 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5TvxH8y9L2QD48w6Y:-Mx9VUONEUb0jm5AehyY:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/284a5fc664a84384de64c72ee719ccb2d3334bec/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/BooleanToExporterEnabledStateConverter.java#L9)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Could you add a short comment why this class was originally used and is now deprecated?
</blockquote></details>

Done.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/PrometheusExporterSettings.java, line 32 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5NmBECo0GdI1ZI92y:-Mx8nYGA4RperzG7WMuo:bb7h6n5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/PrometheusExporterSettings.java#L32)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Why did you change this to `@Min(1)`?
</blockquote></details>

As discussed, in the EUM-Server's PrometheusExporterService there was a now removed if-statement whether the port-number was unequal 0, and after talking with Marius, I removed that while instead enforcing it with the already existing annotations here in the settings.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java, line 46 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MvsuHv46sHexEB_NHmn:-Mx8oSJI8s8ts2gvjM89:bdblg2j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java#L46)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

does this mean that the deserialization of the configuration will throw exceptions if these fields are not set?
We can talk in tomorrow's standup briefly whether we want to explicitly log warnings for all fields that should be set but are not set if `ENABLED` is set.
</blockquote></details>

Yes, as discussed, due to the `notblank` annotation a (not very expressive) exception will be thrown if the fields are not set or set to an empty string, before this if-statement is ever reached.
___
*[inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md, line 10 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5N467-TCSJZCfP12a:-Mx8lOEt2_vxf2xYkBAL:b-bucail) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md#L10)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

rather `flag` or `property` than `field`?
</blockquote></details>

Done.
Yeah, it probably should be property, since that is what it's called elsewhere in the docs.
___
*[inspectit-ocelot-documentation/docs/metrics/metric-exporters.md, line 73 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5RMJl7vwmwSrpuU69:-Mx8kTgt5SytdTgvGIuS:b-q67t44) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/284a5fc664a84384de64c72ee719ccb2d3334bec/inspectit-ocelot-documentation/docs/metrics/metric-exporters.md#L73)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

does it log an error or a warning?

I would also change 
> with IF_CONFIGURED

to

> if set to `IF_CONFIGURED`

Another note: shall we format `ENABLED`, `DISABLED`, and `IF_CONFIGURED` to code formatting?


This comment also applies to the other metrics/trace exporter configuration documentations
</blockquote></details>

Done.
It does log a warning, I forgot to also update the documentation when making that change after talking about it with Marius.
And I agree, they should probably be code formatted in the Description column too :)
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/ExporterEnabledState.java, line 10 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5MWpD9T6qXH541mz1:-Mx8vf_b7rgtwxghm5LL:bmxzk8i) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/ExporterEnabledState.java#L10)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we rather want to rename the enum to `ExporterState` and then `IF_CONFIGURED` to `ENABLED_IF_CONFIGURED`? 

Let's discuss in tomorrow's standup.
</blockquote></details>

Done.
As discussed in the standup, we'll keep the naming as is.


<!-- Sent from Reviewable.io -->

2022-03-02 15:00 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 12 of 36 files reviewed, 12 unresolved discussions (waiting on @aaronweissler, @heiko-holz, and @notblank)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java, line 46 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx8U_-f1KmPcVZ5s137:-Mx9aSpEATWGUgwhY1bi:b-axnlqk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4f31dde829433edf287cf0a0c6d1d18bdbf65c85/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java#L46)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Would it make sense to have a test class for `TraceExportersConfiguration.java` and test the conditions for `public SpanExporter jaegerSpanExporter()`?
</blockquote></details>

I agree, it would be a good idea.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceIntTest.java, line 75 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5QA-Y1KISx5DvaPxe:-MxA8MqZ5mlVNKahg1x1:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceIntTest.java#L75)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

see comment for inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java
</blockquote></details>

Done.



_Code quote (from components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java):_
```Java
StringUtils
```
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java, line 142 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5Qqf50rkh_3v3LUDc:-MxA8NLh2mD_ixXkTGqn:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/284a5fc664a84384de64c72ee719ccb2d3334bec/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java#L142)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

see comment for inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java, line 218 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mx5MkF_3loNdn6qo5zD:-MxA8O5n0qN_OF74NM0z:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/498d484eb90c8e620932b16c65e6f4fbab128348/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java#L218)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I thinkt it would be better to just count the number of warnings. If we change the warning message, we will always have to copy&paste it to the test cases as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 06:57 UTC, heiko-holz reviewed
> Reviewed 11 of 19 files at r8, 2 of 5 files at r9, 5 of 5 files at r11, 6 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: 31 of 36 files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @heiko-holz)



<!-- Sent from Reviewable.io -->

2022-03-03 13:22 UTC, heiko-holz submitted a review, later dismissed
> Reviewed 5 of 5 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)



<!-- Sent from Reviewable.io -->

2022-03-03 13:25 UTC, heiko-holz approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)



<!-- Sent from Reviewable.io -->

2022-03-03 13:28 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java, line 16 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-MxExNWVCSWBM1PjVXON:-MxExNWVCSWBM1PjVXOO:bn6kl0r) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/40106210293efba27d5bcb97cf6db566df1f6d77/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java#L16)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> @Validated
> public class EumExportersSettings extends ExportersSettings {
> ```

We decided to remove the inheritance and instead insert the `metrics` field directly here, because both the superclass and this class had a field called "tracing" leading to issues with Spring loading properties.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java, line 5 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303#-Mvsup043OdYAe8HRzqI:-MxEw7Vc7dntK61xpBU6:bpj12u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/de733c9916a1eda2fa0bd43ee17364497d5948ba/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java#L5)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Just for understanding: we use `org.springframework.util.StringUtils` in favor of `org.apache.commons.lang3.StringUtils` because the former is more recent?
</blockquote></details>

Yes. As discussed, we also will decide on unifying the usage at different places in the project in a new issue.


<!-- Sent from Reviewable.io -->

2022-03-03 13:30 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)



<!-- Sent from Reviewable.io -->

2022-03-03 14:16 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1303)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)



<!-- Sent from Reviewable.io -->

2022-03-03 14:18 UTC, merged