Closes #1297 - Add exporter services and their registration with OpenTelemetry
inspectIT/inspectit-ocelot pull request #1375
Opened 2022-03-30 11:41 UTC by heiko-holz

2022-03-30 11:44 UTC, heiko-holz commented
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml, line 55 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-MzPcigk7S-GLXTOV9d_:-MzPcigk7S-GLXTOV9da:b-48mr03) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/560b1a6fc9786ecb8bdac0f8fb36e384375f9275/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml#L55)):*
> ```YAML
>         endpoint: null
>         # the transport protocol, e.g., grpc or http/protobuf
>         protocol: grpc
> ```

What should be the default value for `protocol`? 
We can either use `null` so that the `protocol` **and** the `endpoint` need to be specified in order to start the exporter, or we could use the following default values:

* jaeger: `http/thrift`
* otlp: `grpc`


<!-- Sent from Reviewable.io -->

2022-04-05 06:21 UTC, heiko-holz commented
You can find the most important changes as well as an architectural description in the attached file

[2022-01-11-ticket-1269-1279-otel-exporters-otel-upgrade-changenotes.pdf](https://github.com/inspectIT/inspectit-ocelot/files/8415467/2022-01-11-ticket-1269-1279-otel-exporters-otel-upgrade-changenotes.pdf)

2022-04-27 04:47 UTC, mariusoe requested changes
> Reviewed 7 of 78 files at r4, 91 of 120 files at r5, 4 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 102 of 127 files reviewed, 69 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java, line 47 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FjaJjD-Sl_mhHoAwf:-N0FjaJjD-Sl_mhHoAwg:b2equmn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java#L47)):*
> ```Java
>     @ConditionalOnExpression("(NOT new String('${inspectit-eum-server.exporters.tracing.jaeger.enabled}').toUpperCase().equals(T(rocks.inspectit.ocelot.config.model.exporters.ExporterEnabledState).DISABLED.toString())) AND (new String('${inspectit-eum-server.exporters.tracing.jaeger.endpoint}').length() > 0)")
>     public SpanExporter jaegerSpanExporter() {
>         @Valid JaegerExporterSettings jaegerExporterSettings = configuration.getExporters().getTracing().getJaeger();
> ```

Is this inline annotation having an effect at all?



_Code quote:_
```Java
@Valid 
```
___
*[inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java, line 4 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0Fk_jH3N4GE_hLpwq0:-N0Fk_jI9_ewxlu8ZCEz:b1rvp87) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L4)):*
> ```Java
> 
> import lombok.AllArgsConstructor;
> import lombok.Value;
> ```

Revert please - don't needed.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java, line 36 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FkiNsCHyPcSzZnGWj:-N0FkiNsCHyPcSzZnGWk:b8bpwhx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java#L36)):*
> ```Java
>     @Test
>     public void logStringAndTraceExists() {
>         System.out.println(String.format("OTEL=%s, tracer=%s", Instances.openTelemetryController.getClass()
> ```

Use the `LOGGER` for logging
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 238 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6S23DFLGOwGdTAS6:-N0G6S23DFLGOwGdTAS7:buara6k) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L238)):*
> ```Java
>      * Waits for the initialization of {@link rocks.inspectit.ocelot.core.opentelemetry.OpenTelemetryControllerImpl}, which is then registered to {@link Instances#openTelemetryController}
>      */
>     public static void waitForOpenTelemetryControllerInitialization() {
> ```

As far as I can see, this is not used.
___
*[inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java, line 240 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6RZk3BMYsI6Cd55V:-N0G6RZk3BMYsI6Cd55W:b-e00bji) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L240)):*
> ```Java
>     public static void waitForOpenTelemetryControllerInitialization() {
>         Awaitility.await().atMost(30, TimeUnit.SECONDS).untilAsserted(() -> {
>             assertThat(NoopOpenTelemetryController.INSTANCE != Instances.openTelemetryController).isTrue();
> ```

`assertThat(Instances.openTelemetryController).isNotEqualTo(NoopOpenTelemetryController.INSTANCE);`
___
*[inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java, line 6 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6nAn17Ppjb4-5D9k:-N0G6nAn17Ppjb4-5D9l:b-2fw6gd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L6)):*
> ```Java
>  * Controller interface for the OpenTelemetryController. Its implementation is {@link rocks.inspectit.ocelot.core.opentelemetry.OpenTelemetryControllerImpl}
>  */
> public interface IOpenTelemetryController {
> ```

Use just `OpenTelemetryController`. We don't use the `I` prefix because the implementation is suffixed with `Impl`. Imo we should not use both "markers".



_Code quote:_
```Java
IOpenTelemetryController
```
___
*[inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java, line 13 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GAT2u8-TcZgpMsOAQ:-N0GAT2u8-TcZgpMsOAR:bkczub5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L13)):*
> ```Java
>      * @return
>      */
>     static IOpenTelemetryController noop() {
> ```

Not used and needed. We can directly use the Noop instance with `NoopOpenTelemetryController.INSTANCE` when needed.
___
*[inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java, line 22 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GADAF2iHEWUl8ScRT:-N0GADAF2iHEWUl8ScRU:bra9yp2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L22)):*
> ```Java
>      * @return Whether the {@link IOpenTelemetryController} is configured
>      */
>     boolean isConfigured();
> ```

Is this only used for testing?
___
*[inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java, line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G7L_h4TZpzJ4kUZK8:-N0G7L_h4TZpzJ4kUZK9:b-shfnam) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L29)):*
> ```Java
>      * @return Whether the {@link IOpenTelemetryController} is enabled
>      */
>     boolean isEnabled();
> ```

In my opinion, the names are not unique as to what the return value indicates. 

At first glance, we have the following "states":
- enabled
- configured
- started
- stopped
- shutdown

But as far as I can see in the code, enable is actually equal to started and configured, right? And stopped means that the controller has been shut down.
Maybe we can use something like:

- isStarted()
- start()
- has/isShutdown()
- shutdown()
___
*[inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java, line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GALf83MBdAQbReWrh:-N0GALf83MBdAQbReWri:bra9yp2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L29)):*
> ```Java
>      * @r [...]

2022-05-02 09:09 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 102 of 127 files reviewed, 69 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[`components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java` line 47 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FjaJjD-Sl_mhHoAwf:-N0jQ-qt544ilI9ph6u8:b-3940nh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java#L47)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Is this inline annotation having an effect at all?
</blockquote></details>

That's a good point!

Let's discuss whether we need the `@Valid` annotations in any other class using the settings if they are already set in the `MetricsExporterSettings.java` and `TraceExporterSettings.java`
___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 4 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0Fk_jH3N4GE_hLpwq0:-N12Fm7l2J9-jTTF8XHf:buyrj0i) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L4)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Revert please - don't needed.
</blockquote></details>

Thanks for pointing this out. Unused imports are now removed (and thus the changes are reverted)
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java` line 238 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6S23DFLGOwGdTAS6:-N12JP0AB5Fdnp_LvYkp:b-j8okvp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L238)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As far as I can see, this is not used.
</blockquote></details>

You are right. This method was used in previous version, but now it is not used anymore. 
I removes this method.
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java` line 240 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6RZk3BMYsI6Cd55V:-N12JWO-2z_lKBRE8j9K:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java#L240)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

`assertThat(Instances.openTelemetryController).isNotEqualTo(NoopOpenTelemetryController.INSTANCE);`
</blockquote></details>

Done.
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 6 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6nAn17Ppjb4-5D9k:-N12Jcpf9teQS3hgcqOQ:b-i7jru0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L6)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Use just `OpenTelemetryController`. We don't use the `I` prefix because the implementation is suffixed with `Impl`. Imo we should not use both "markers".
</blockquote></details>

The `I` prefix is sometimes used, e.g., `IGenericAction`, `IHookManager`, `IMethodHook`.

Let's discuss this in our weekly.

-> create github issue for consistent interface naming
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 13 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GAT2u8-TcZgpMsOAQ:-N12KieuDlPoRa96ul31:b-84a3m2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L13)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Not used and needed. We can directly use the Noop instance with `NoopOpenTelemetryController.INSTANCE` when needed.
</blockquote></details>

I agree. I was somewhat following the coding standards of OpenTelemetry but still references `NoopOpenTelemetryController.INSTANCE`.

What do you think is more suitable: dropping the `IOpenTelemetry.noop()` method (and being more in line with other implementations in inspectIT Ocelot) or keeping and using it instead of `NoopOpenTElemetryController INSTANCE` (aligning it to the code of OpenTelemetry)
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 22 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GADAF2iHEWUl8ScRT:-N12_PP7CmODuPSwsebt:b-iwrsp8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L22)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Is this only used for testing?
</blockquote></details>

Originally, I wanted to implement a method that reliably tells whether the `IOpenTelemetryController` is configured and ready to run. The method is currently only used in test classes.

Howeve, I use the implementation `@Getter private boolean configured` in `OpenTelemetryControllerImpl` to decide whether OpenTelemetry ( `OpenTelemetryImpl`, `SdkMeterProvider`, `SdkTracerProvider` and `OpenTelemetrySdk`) needs to be configured. 

Should I rather use the method `isConfigured()` in the implementation so that the usage can be detected more easily?
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G7L_h4TZpzJ4kUZK8:-N12bNZz1IC953WLgVUw:b-fsu7w5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L29)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

In my opinion, the names are not unique as to what the return value indicates. 

At first glance, we have the following "states":
- enabled
- configured
- started
- stopped
- shutdown

But as far as I can see in the code, enable is actually equal to started and configured, right? And stopped means that the controller has been shut down.
Maybe we can use something like:

- isStarted()
- start()
- has/isShutdown()
- shutdown()
</blockquote></details>

You are almost correct.

`enabled` equals `started` (which is not a state in my current implementation) and tells us whether the `IOpenTelemetryController` has started and is not `stopped` (shut down). It does not necessarily mean that it is already `configured`.

What do you think about the following:
* isStarted()
* start()
* isConfigured()
* isShutDown()
* shutdown()
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GALf83MBdAQbReWrh:-N12cjA5ALzknpaEEyiq:b-xnraae) ([raw file](ht [...]

2022-05-02 09:34 UTC, mariusoe requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 102 of 127 files reviewed, 66 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 6 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6nAn17Ppjb4-5D9k:-N131bXh-Ctu9bt0WcOh:b-wltnd0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L6)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

The `I` prefix is sometimes used, e.g., `IGenericAction`, `IHookManager`, `IMethodHook`.

Let's discuss this in our weekly.

-> create github issue for consistent interface naming
</blockquote></details>

-> create github issue for consistent interface naming
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 13 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GAT2u8-TcZgpMsOAQ:-N131jE-3Q_Dc6qHrZEM:bszucwa) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L13)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I agree. I was somewhat following the coding standards of OpenTelemetry but still references `NoopOpenTelemetryController.INSTANCE`.

What do you think is more suitable: dropping the `IOpenTelemetry.noop()` method (and being more in line with other implementations in inspectIT Ocelot) or keeping and using it instead of `NoopOpenTElemetryController INSTANCE` (aligning it to the code of OpenTelemetry)
</blockquote></details>

As discussed, let's keep it consistent with the current code base for now.
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G7L_h4TZpzJ4kUZK8:-N134SmB6-eBMRjI_zfn:bce6gj9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L29)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

You are almost correct.

`enabled` equals `started` (which is not a state in my current implementation) and tells us whether the `IOpenTelemetryController` has started and is not `stopped` (shut down). It does not necessarily mean that it is already `configured`.

What do you think about the following:
* isStarted()
* start()
* isConfigured()
* isShutDown()
* shutdown()
</blockquote></details>

As discussed, let's rename `isConfigured` to `isActive` and rethink whether `isStarted` is necessary.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToTransportProtocolConverter.java` line 14 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0Fby-OBEkKgXSkGAPF:-N135lh_54vIL_V2zwGd:blijj58) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToTransportProtocolConverter.java#L14)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

It depends on the values that we want to use in the configuration yaml.

I opted for the same wording as OpenTelemetry, which is `grpc`, `http/thrift`, `http/protobuf`, and `http/json`.
Due to the slash, I have to implement a custom parse that parses these strings into their enum representation.

To get rid of the `StringToTransportProtocolConverter`, we would need to change from using `/` in the protocols to `_`, which is not in line with the naming of OTEL.
</blockquote></details>

Add documentation to the class stating this.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java` line 12 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FbU_11R5jT-cyrBsy:-N1365jo9xkFucl31Io1:b-h1kvun) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java#L12)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I removed the unused `HTTP_JSON`. 
Regarding `UNKNOWN` and `COUNT`, let's discuss this the weekly
</blockquote></details>

As discussed, please remove :) 
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java` line 37 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0Fbk_BErM9Lg7iQbAJ:-N1368z_95X6xQRDfKCu:b32wtd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java#L37)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

See comment above.

I use this so that we can use `/` in the protocols to be in line with the naming of OTEL.
</blockquote></details>

ok
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java` line 35 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FfF4JAx1W2mFZWwTz:-N136aFY83UVcd6PKd06:b9egayd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java#L35)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Good point.

Can we implement a generic Validator for Enum?

As far as I am aware, we can only implement a specific Validator for specific enums, e.g., for `TransportProtocol` it would look like this:

```Java
/**
 * Validate that an {@link TransportProtocol} is in the supported array of {@link #anyOf()}.
 * Will fail if a property is not in {@link #anyOf()}.
 */
@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE})
@Retention(RUNTIME)
@Documented
@Constraint(validatedBy = TransportProtocolSubsetValidator.class)
public @interface TransportProtocolSubset {

    TransportProtocol[] anyOf();

    String message() default "must be any of {anyOf}";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}

```

```Java
/**
 * Validator for {@link TransportProtocolSubset}
 */
public class TransportProtocolSubsetValidator implements ConstraintValidator<TransportProtocolSubset, Enum> {

    private TransportProtocol[] subset;

    @Override
    public void initialize(TransportProtocolSubset constraintAnnotation) {
        subset = constraintAnnotation.anyOf();
    }

    @Override
    public boolean isValid(Enum value, ConstraintValidatorContext context) {
        return Arrays.asList(subset).contains(value);
    }
}
```
</blockquote></details>

Let's do this


<!-- Sent from Reviewable.io -->

2022-05-05 13:17 UTC, heiko-holz reviewed
> Reviewed 3 of 120 files at r5.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 82 of 131 files reviewed, 66 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 6 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G6nAn17Ppjb4-5D9k:-N1IDhyj0nxjQpkA528R:bhpycg3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L6)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

-> create github issue for consistent interface naming
</blockquote></details>

done: https://github.com/inspectIT/inspectit-ocelot/issues/1421
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 13 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GAT2u8-TcZgpMsOAQ:-N13wcvWDSIKNkaFBDTN:bwe5vmy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L13)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As discussed, let's keep it consistent with the current code base for now.
</blockquote></details>

I removed the `IOpenTelemetry.noop()`
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 29 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0G7L_h4TZpzJ4kUZK8:-N13zsqj9B-Loxr5lRwd:b-8e64yt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L29)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As discussed, let's rename `isConfigured` to `isActive` and rethink whether `isStarted` is necessary.
</blockquote></details>

I renamed `isConfigured` to `isActive`and removed the `isEnabed`/`isStarted` property.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToTransportProtocolConverter.java` line 14 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0Fby-OBEkKgXSkGAPF:-N18Lu252g8qM06EhQ6P:b-r2hp2d) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToTransportProtocolConverter.java#L14)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Add documentation to the class stating this.
</blockquote></details>

I added a more detailed class documentation as well as an additional comment to `configRepresentation`.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java` line 12 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FbU_11R5jT-cyrBsy:-N18MDjOCChAuwGDwkSf:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/TransportProtocol.java#L12)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

As discussed, please remove :) 
</blockquote></details>

Done.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/InfluxExporterSettings.java` line 34 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FeyeM8NV2Mjzlxn3Z:-N1IN0qRADOaXjt_odHa:bgbzqt9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/InfluxExporterSettings.java#L34)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

See comment in `InfluxExporterService`

-> depending whether we support InfluxDB in the future, we should already add a deprecation warning or something like that.
</blockquote></details>

In case we decide to deprecate `InfluxExporterService` in version `2.X`, would you add the deprecation warning to the `Settings` or `Service`class?
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java` line 35 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FfF4JAx1W2mFZWwTz:-N1INFtq7ExSiWBqs-3w:bu9qo2e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java#L35)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's do this
</blockquote></details>

Actually, as discussed, it is not as easy as I thought.

If we want to have the validation in the `Settings` class using annotations, we need to discuss the following points:

* shall the validation also apply when the exporter is disabled? 
    * depending on the default value, this results in additional requirements such as conditional validation, see comments below
* what is the default value of `protocol`?
    * currently, we use `null` as the default value so that the user has to specify it (which I think is fine in case the exporter is disabled). However, using `null` as the default value for disabled exporter would result in conditional validation, which needs to be implemented additionally 
    * if we decide to use a supported value as default (e.g., `grpc`), then we need to set it in the `exporter.yml`.
    * if we decide to use `unset` as the default value, I need to add it to the list of supported protocols and implement an additional conditional validation that checks that the value is not `unset` if the exporter is enabled

Another option for the validation in the `Settings` class could be the `@AdditionalValidations` and  `@AdditionalValidation` annotation, e.g.,

```Java
@AdditionalValidations
public class OtlpMetricsExporterSettings{
[....]

 private static List<TransportProtocol> SUPPORTED_PROTOCOLS = Arrays.asList(TransportProtocol.GRPC, TransportProtocol.HTTP_PROTOBUF);

    @AdditionalValidation
    public void performValidations(ViolationBuilder vios) {
        if (enabled.equals(ExporterEnabledState.ENABLED)) {
            if (!SUPPORTED_PROTOCOLS.contains(protocol)) {
                vios.atProperty("protocol")
                        .message("Unsupported value '{protocol}' for property 'protocol'. Supported values are {values}")
                        .parameter("protocol", protocol)
                        .parameter("values", Arrays.toString(SUPPORTED_PROTOCOLS.toArray()))
                        .buildAndPublish();
            }
        }
    }
}
```

I think we can implement the conditional validation in the `performValidations` method. But I honestly don't know whether it is advantageous having such a validation in the `Settings` class rather than in the `Service` class (which is technically not the same as validating the inputs).

If we decide to use validation, we need to consider that the configuration is rejected as soon as one validation fails (currently, the configuration is still accepted and only the ill-defined exporters are disabled) 

Let's discuss this.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/JaegerEx [...]

2022-05-06 06:44 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 82 of 131 files reviewed, 66 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java` line 36 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FkiNsCHyPcSzZnGWj:-N12HDIr9fECOV6YQ8A9:b-a8272) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java#L36)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Use the `LOGGER` for logging
</blockquote></details>

I removed the unnecessary debug log statement. Using `LOGGER` breaks the tests (as it asserts on the `Log42JoggingRecorder.loggingEvents`).

General question: when do we use `LoggerFactory.getLogger(Class.class)`, `Logger.getLogger(Class.class.getName())`, and when `LogManager.getLogger(Class.class)` (from `org.apache.log4j`) ?

Let's create a github issue that investigates the use of different logging frameworks / access to a logger to see if we inconsistently use different libraries / calls to retrieve a logger. As a result of the ticket, we could have a table detailing in which content which library/call is used.


<!-- Sent from Reviewable.io -->

2022-05-11 21:57 UTC, mariusoe requested changes
> Reviewed 25 of 38 files at r7, 2 of 3 files at r8.
> Dismissed @heiko-holz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375)* status: 99 of 131 files reviewed, 9 unresolved discussions (waiting on @heiko-holz and @mariusoe)

___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/InfluxExporterSettings.java` line 34 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FeyeM8NV2Mjzlxn3Z:-N1ngkQv4iHZGrOW57Oj:be11r1t) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/InfluxExporterSettings.java#L34)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

In case we decide to deprecate `InfluxExporterService` in version `2.X`, would you add the deprecation warning to the `Settings` or `Service`class?
</blockquote></details>

We keep the exporter for now.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/JaegerExporterSettings.java` line 43 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FhpPv6Vnh2fMcSQo2:-N1NmN7d3VoxO_xgYrvH:bvtwtbm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/JaegerExporterSettings.java#L43)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I agree. 

I forgot to remove it from `OtlpTraceExporterSettings` and `LoggingTraceExporterService` (the property was not used and was also not in the documentation of these exporters).

Regarding the `JaegerExporterSettings`, I am not sure how the `TraceExportersConfiguration` in the EUM component needs to be changed, as I did not implement that class. 
Should I move this property up to the `EumServerConfiguration`?
</blockquote></details>

You should be able to remove this because the EUM server is not using a service name. The service name of the EUM spans are already specified by the EUM agent, thus we don't need it there.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TracingSettings.java` line 63 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FibRN-Jxup6W5hmAs:-N1NmuSTErsP7s84-LqT:bm0siyo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TracingSettings.java#L63)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Thanks for pointing this out.

I was following the coding convention of OTEL (e.g., https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBuilder.java).

If I am not mistaken, the code base mostly has the default values in the default configuration files, and does not set them in the code.  
Thus, I removed the static fields and moved the value into the  `basics.yml` of the default configuration. 

However, the code base is not consistent. For example, the default value for`TracingSettings#propagationFormat` is also set in the code and in the default configuration.

What do you think, where should the default value be specified?
- directly in the field
- in the default configuration
- in both places
</blockquote></details>

Let's keep it as you did in the latest version. We need to discuss this with the team.
___
*[`inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml` line 55 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-MzPcigk7S-GLXTOV9d_:-N1nh-GPDz0LBQjXOrzP:b-zamm6a) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/560b1a6fc9786ecb8bdac0f8fb36e384375f9275/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml#L55)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I am not sure about using `unset` (using lower case to be consistent with the configuration; it will still be correctly parsed). 
`null` clearly states that this value has not been set.

We also have been using `null`for  other String properties before (e.g., `endpoint`, `user`, `password` etc.).

But I don't have a strong opinion with this.

</blockquote></details>

let's use null
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/DynamicallyActivatableMetricsExporterService.java` line 21 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0GK5wrBTWvCTBVZSCE:-N1NpDqr8RePKuBp6ZvC:b-lrlxjp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/DynamicallyActivatableMetricsExporterService.java#L21)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I actually need to register something that offers a method that returns a **new** `MetricReaderFactory`.

When the `SdkMeterProvider` is shut down during the re-configuration of the `OpenTelemetryControllerImpl`, the previously registered `MetricReaderFactory` are also closed and cannot be re-used.
I therefore need to create a new `MetricReaderFactory` during `OpenTelemetryControllerImpl#configureMeterProvider(InspectitConfig configuration)`.

As alternative to the `DynamicallyActivatableMetricsExporterService` class, we can also use a `Callable<MetricReaderFactory` as parameter of the `registerMetricExporterService(Callable<MetricReaderFactory> newMetricReaderFactoryProvider, String serviceName`. 

What do you think?
</blockquote></details>

Ok, got it. But then let's not name it `get..`, as this may not be understood correctly ( as it was the case with me :) ).
What about `createMetricReaderFactory`? This clearly states that it creates a new factory.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java` line 24 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N0FeL-6AN90WFEhPK1I:-N1neCaU57nRuX_ugn0a:b-eajg9h) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d2eff036e838dadfa25162344c120b784e0506c9/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java#L24)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

It it working with the OTEL-OC-Shim (although the `InfluxExporterServiceIntTest` still does not work reliably in a local development environment).

I also think that we do not need to provide an InfluxDB exporter as the OTEL Collector provides one (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/influxdbexporter). 
We can then just point to the OTEL Collector.
</blockquote></details>

Let's keep it for now, so the migration is easier
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java` line 50 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1375#-N1Nqcj46eSFWV1DgaFF:-N1Nqcj46eSFWV1DgaFG:bqmqb3b) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/204042a72d4fbaeb64ca07e5b67db2784c86e6a7/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java#L50)):*
> ```Java
>             if ((null == jaeger.getProtocol() || jaeger.getProtocol()
>                     .equals(TransportProtocol.UNSET)) && (StringUtils.hasText(jaeger.getUrl()) || StringUtils.hasText(jaeger.getGrpc()))) {
>                 jaeger.setProtocol(StringUtils.hasText(jaeger.getUrl()) ? TransportProtocol.HTTP_THRIFT : TransportProtocol.G [...]

2022-05-13 14:10 UTC, merged