Export metric about duration of JDBC queries
inspectIT/inspectit-ocelot pull request #1420
Opened 2022-05-03 15:08 UTC by Henning-Schulz

The provided changes collect the metric jdbc/query/duration with views sum and count. The labels are the requested database (`jdbc_url`), the command like SELECT, UPDATE, ... (`sql_command`) and the called JDBC method (`jdbc_operation`).

The metric is a missing counterpart to the JDBC span collection.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)

2022-05-30 13:15 UTC, MariusBrill requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Henning-Schulz and @mariusoe)

___
*[`inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/db/jdbc.yml` line 50 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420#-N3K5AtI77Y48zwlrNy3:-N3K5AtI77Y48zwlrNy4:b-jy6hyc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dfc7276028bc70fe7dd6a2a8fc2e46e5195aeaa2/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/db/jdbc.yml#L50)):*
> ```YAML
>         value-body: |
>           int index = statement.indexOf(' ');
>           if (index > -1) {
> ```

Wouldn't this mean a query like " SELECT ..." would not work? Should we set the comparison in the if-statement to index > 0?


<!-- Sent from Reviewable.io -->

2022-05-31 12:18 UTC, mariusoe approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)* status: all files reviewed, 1 unresolved discussion (waiting on @Henning-Schulz)



<!-- Sent from Reviewable.io -->

2022-05-31 12:18 UTC, mariusoe approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)* status: all files reviewed, 1 unresolved discussion (waiting on @Henning-Schulz)



<!-- Sent from Reviewable.io -->

2022-05-31 12:25 UTC, MariusBrill approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Henning-Schulz)



<!-- Sent from Reviewable.io -->

2022-05-31 12:29 UTC, merged