feat: Implemented functionality to support synchronous instrumentation
inspectIT/inspectit-ocelot pull request #1501
Opened 2022-07-22 07:40 UTC by ClaudioWaldvogel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)

2022-11-04 15:00 UTC, heiko-holz requested changes
> Reviewed 34 of 36 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: all files reviewed, 45 unresolved discussions (waiting on @ClaudioWaldvogel and @MariusBrill)

___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 49 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwdz_c0VaqTyYagm3B:-NFwdz_c0VaqTyYagm3C:bgy8w3k) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L49)):*
> ```Java
>     private static final String ASYNC_INSTRUMENTATION_PROPERTY = "inspectit.instrumentation.internal.async";
> 
>     private static final String ASYNC_INSTRUMENTATION_ENV_PROPERTY = "INSPECTIT_INSTRUMENTATION_INTERNAL_ASYNC";
> ```

We could alternatively compute the value:
`private static final String ASYNC_INSTRUMENTATION_ENV_PROPERTY = ASYNC_INSTRUMENTATION_PROPERTY.toUpperCase().replaceAll(".","_")`

Do we even need the environment variable or does Spring parse it appropriately already with the `ASYNC_INSTRUMENTATION_PROPERTY`?
___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfPWv4KIyWsGzfl6l:-NFwfPWv4KIyWsGzfl6m:bhp40oo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L96)):*
> ```Java
>             } else {
>                 String javaVersion = System.getProperty("java.version");
>                 if (javaVersion.startsWith("1.8")) {
> ```

why are we printing the error message here?

In this branch, the async instrumentation is `disabled`, thus we are instrumenting `synchronously`.
___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 173 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfg-EAvBbCZ7dDYII:-NFwfg-EAvBbCZ7dDYIJ:bd8d7u9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L173)):*
> ```Java
> 
>         static {
>             ClassLoader.registerAsParallelCapable();
> ```

why do we need this?
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/IAgent.java` line 8 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfrbf40MhRs1gxFD1:-NFwfrbf40MhRs1gxFD2:b-ay1vp7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/IAgent.java#L8)):*
> ```Java
>  * Controller interface for the Agent. Its implementation is {@link rocks.inspectit.ocelot.core.AgentImpl}.
>  * The implementation must provide a default cosntructor without side effects!
>  * The actual initialization should happen in {@link #start(String, Instrumentation, boolean)}, which is called by {@link AgentManager}
> ```

current version of `start(String agentCmdArgs, Instrumentation instrumentation)` does not have a boolean argument.
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java` line 61 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwgCMYAR-zX-kmQRhe:-NFwgCMYAR-zX-kmQRhf:b-hsx89k) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java#L61)):*
> ```Java
> 
>     /**
>      * Flag ensures synchronous instrumentation of class. This means, each class is instrumented on first class load.
> ```

doesn't this flag enable `synchronous` and `asynchronous` instrumentation?

By default, `asynchronous` is enabled
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java` line 36 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwgmII9pWFeVdnlxgP:-NFwgmII9pWFeVdnlxgQ:bo2ft89) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java#L36)):*
> ```Java
>     public static final ClassLoader AGENT_CLASS_LOADER = AgentImpl.class.getClassLoader();
> 
>     public static final TypePool AGENT_CLASS_LOADER_TYPE_POOL = TypePool.Default.of(AGENT_CLASS_LOADER);
> ```

why do we need the `TypePool`?

A short comment would be nice.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java` line 11 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwhRfq9EV0YzlgnyZh:-NFwhRfq9EV0YzlgnyZi:b-yqvoo0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java#L11)):*
> ```Java
> /**
>  * Container for {@link TypeDescription}s and {@link  ClassLoader} pairs.
>  * The purpose of this container is to have common type for already loaded classes and for classes loading for the first time
> ```

Why is this a `container`? Should this be reflected in the name of the class?
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java` line 58 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxVA0AEvm8nkEUjhu0:-NFxVA0AEvm8nkEUjhu1:bi7uqx4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java#L58)):*
> ```Java
>      * @return new {@link TypeDescriptionWithClassLoader}
>      */
>     public static TypeDescriptionWithClassLoader of(String className, ClassLoader loader) {
> ```

what was the previous equivalent with ByteBuddy to load an unloaded type?

Maybe we should adhere to the same architecture, i.e., having a subclass `ForLoadedType` and whatever was/is used for unloaded types.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 75 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxZ-JeDqRvtZ2u7tUR:-NFxZ-JeDqRvtZ2u7tUS:bparvsj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L75)):*
> ```Java
>     /**
>      * Builds the {@link ClassInstrumentationConfiguration} based on the currently active global instrumentation configuration
>      * for the given class.
> ```

does this need to be adjusted to `for the given type description with class loader` or sth?
Maybe also add somewhere to the comment that it's for unloaded classes, if this is the case.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 117 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxZVaw8SnQ_2yvLgfz:-NFxZS5c034wSusim_iX:b-p4t2ks) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L117)):*
> ```Java
> 
>     /**
>      * Finds out for each method of the given class which rules apply and builds a {@link MethodHookConfiguration} for each instrumented method.
> ```

I thi [...]

2022-11-11 10:36 UTC, ClaudioWaldvogel reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: 18 of 40 files reviewed, 35 unresolved discussions (waiting on @heiko-holz and @MariusBrill)

___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 49 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwdz_c0VaqTyYagm3B:-NG2AofxElO_3Rtgex6w:b-2pt4l5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L49)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

We could alternatively compute the value:
`private static final String ASYNC_INSTRUMENTATION_ENV_PROPERTY = ASYNC_INSTRUMENTATION_PROPERTY.toUpperCase().replaceAll(".","_")`

Do we even need the environment variable or does Spring parse it appropriately already with the `ASYNC_INSTRUMENTATION_PROPERTY`?
</blockquote></details>

At this point Spring is not yet intialized
___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfPWv4KIyWsGzfl6l:-NG2BL28BplccyzC7OUE:b-61gm6e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L96)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why are we printing the error message here?

In this branch, the async instrumentation is `disabled`, thus we are instrumenting `synchronously`.
</blockquote></details>

The message says that async is disabled in pre Java 9 environments and this will have significant performance degradations
___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 173 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfg-EAvBbCZ7dDYII:-NGH5eJe2RWNigBNyk9R:bd48k5p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L173)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

Due to rocks.inspectit.ocelot.core.instrumentation.InstrumentationTriggerer we have seen race conditions in class loading and thus we enabled InspecTIClassLoader as parallel callable
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/IAgent.java` line 8 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfrbf40MhRs1gxFD1:-NGH85cTDPOs0a1yjfpw:bb6un1j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/IAgent.java#L8)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

current version of `start(String agentCmdArgs, Instrumentation instrumentation)` does not have a boolean argument.
</blockquote></details>

Done
___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java` line 61 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwgCMYAR-zX-kmQRhe:-NGH8SRD5H0D-tIwsM3R:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java#L61)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

doesn't this flag enable `synchronous` and `asynchronous` instrumentation?

By default, `asynchronous` is enabled
</blockquote></details>

Done.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java` line 36 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwgmII9pWFeVdnlxgP:-NGH8pR6Bp0tDAYi180I:bb6un1j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java#L36)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why do we need the `TypePool`?

A short comment would be nice.
</blockquote></details>

Done
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java` line 58 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxVA0AEvm8nkEUjhu0:-NGHDZgG8LCQWgeHg-WY:b-c9blne) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java#L58)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

what was the previous equivalent with ByteBuddy to load an unloaded type?

Maybe we should adhere to the same architecture, i.e., having a subclass `ForLoadedType` and whatever was/is used for unloaded types.
</blockquote></details>

Not sure what you mean :)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 75 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxZ-JeDqRvtZ2u7tUR:-NGHE6W1-wQ1pp5mUKtR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L75)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

does this need to be adjusted to `for the given type description with class loader` or sth?
Maybe also add somewhere to the comment that it's for unloaded classes, if this is the case.
</blockquote></details>

Done.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 117 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxZVaw8SnQ_2yvLgfz:-NGHEOq52mKiCL4v3aPh:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L117)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think this javadoc also needs to be adjusted to reflect the `TypeDescriptionWithClassLoader`
</blockquote></details>

Done.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 263 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxXzqyD7wUYgWPs-Mx:-NGHEWq11rHCuuEji_Lu:by1z1zn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L263)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

would it make sense to implement the `isModifiableType` in the `TypeDescriptionWithClassLoader`?
</blockquote></details>

Actually, I don't think so. I  think ```TypeDescriptionWithClassLoader``` should only contain logic to created ```TypeDescription```objects.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 68 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFx_wXIB2eQEs_GJMXT:-NGHFsbzEopj6CXCswNY: [...]

2022-11-11 13:08 UTC, heiko-holz commented
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 49 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwdz_c0VaqTyYagm3B:-NGanU4eAKZQBCX2d1rt:b-xcnspv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L49)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

At this point Spring is not yet intialized
</blockquote></details>

good point :)


<!-- Sent from Reviewable.io -->

2022-11-11 13:10 UTC, heiko-holz commented
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfPWv4KIyWsGzfl6l:-NGanh3z0jSL-6vYR8Tc:b5uotg0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L96)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

The message says that async is disabled in pre Java 9 environments and this will have significant performance degradations
</blockquote></details>

Ahhh, okay so pre Java 9 we should rather do synchronous instrumentation (what you just have implemented).
Got it, thanks!


<!-- Sent from Reviewable.io -->

2022-11-14 09:52 UTC, heiko-holz reviewed
> Reviewed 5 of 15 files at r3, 17 of 17 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: all files reviewed, 9 unresolved discussions (waiting on @ClaudioWaldvogel and @MariusBrill)

___
*[`inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java` line 173 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFwfg-EAvBbCZ7dDYII:-NGao6OR95zMW68gQ_LK:b-kpi4hk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java#L173)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

Due to rocks.inspectit.ocelot.core.instrumentation.InstrumentationTriggerer we have seen race conditions in class loading and thus we enabled InspecTIClassLoader as parallel callable
</blockquote></details>

Okay, thanks for clarifying. Would be great if you added the comment to the source file directly :)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java` line 58 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxVA0AEvm8nkEUjhu0:-NGaoWKl7XUZSd3iNIvZ:b-cb17q2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java#L58)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

Not sure what you mean :)
</blockquote></details>

I think we resolved this in a discussion.

I had the idea that we implement the same `class.staticMethod` structure for the `TypeDescriptionWithClassloader`, so that the access to the `of` method is differently for loaded and for unloaded types.

e.g., by implementing nested classes with names such as `ForLoadedType` and `ForUnloadedType` and then have these two classes implement the `of` method
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java` line 263 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxXzqyD7wUYgWPs-Mx:-NGaozbf6cAGrnQGs10f:b-k4z9z7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java#L263)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

Actually, I don't think so. I  think ```TypeDescriptionWithClassLoader``` should only contain logic to created ```TypeDescription```objects.
</blockquote></details>

Good point :)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 70 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxaXsx7n3t8hf_-SjM:-NGapGhVDpPimdZTlI4s:b-23zl19) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java#L70)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

done
</blockquote></details>

I added the `lazy` to the `hook loading` :)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 75 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxfMpG1gFmgIwD2K2p:-NGapSxTDNw4H9sxommc:b-40v7lv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java#L75)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

Yes. In the default async fashion. Classes are instrumented while those are already loaded and hooks are ensured to be generated when ```HookManager.getHooks()```is invoked for the first time.
Hooks are generated from ```rocks.inspectit.ocelot.core.instrumentation.hook.MethodHookGenerator.buildHooks(Class,MethodDescription,MethodHookConfiguration)```. As you see this relies on already loaded classes.
We did not want to open the Pandorra's box by changing all this generation code. Thus, hooks are generated on the fly if not yet available
</blockquote></details>

thanks for the explanation!
(should we add this to some documentation?)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 81 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxfSIO4ubXYPGfFR0c:-NGaqk7uC5U5G6ekyLAC:b10ca3n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java#L81)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

No, ```hooks```are updated as soon as ```HookManager.HookUpdate.commitUpdate()```is called.
```hooks```is not intended to be updated outside of ```HookManager.HookUpdate```class. 
</blockquote></details>

thanks for the clarification :)
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 138 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxcpg4Cm-Mnjhu4g5d:-NGarHU_0x-vUZma8BZb:bi407ow) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java#L138)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

```lazyHookingPerformed``` ensures  ```lazyHookGeneration()```is invoked only once per class
</blockquote></details>

ah, I see. Mixed this "was already invoked"-lock with a snychronization lock.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java` line 159 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxd46a85ovk2IL7Faz:-NGar7Td1bxH2Thya5H9:b5c6xdc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java#L159)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

This is basically checked before the methods is invoked
</blockquote></details>

Okay, didn't realize that. Thanks for the clarification1
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/transformer/AbstractClassTransformer.java` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFyHJU1Ejz7ja1eVnzB:-NGatBad8mCRj6UN6HJ1:b60znkr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/transformer/AbstractClassTransformer.java#L96)):*
<details><summary><i>Previously, ClaudioWaldvogel (woodywoodse) wrote…</i></summary><blockquote>

Yes in > Java 9 environments. 
This will be invoked from the proxy object created in ```rocks.inspectit.ocelot.core.instrumentation.transformer.ClassTransformerProxyGenerator.createAndInstantiateClassTransformerProxy```
</blockquote></details>

Okay, I think my comment was attached to the wrong method. I see that you removed the unused `transform` method below
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/transfo [...]

2022-11-14 09:52 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: all files reviewed, 6 unresolved discussions (waiting on @ClaudioWaldvogel and @MariusBrill)



<!-- Sent from Reviewable.io -->

2022-11-14 11:53 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: all files reviewed, 5 unresolved discussions (waiting on @ClaudioWaldvogel and @MariusBrill)



<!-- Sent from Reviewable.io -->

2022-11-14 14:13 UTC, heiko-holz commented
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java` line 58 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501#-NFxVA0AEvm8nkEUjhu0:-NGqSw-t3GNxy5tGfJsw:b-v3ycou) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f73d4e4969531b1829792bb5aeb535a909a4e8f/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/TypeDescriptionWithClassLoader.java#L58)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think we resolved this in a discussion.

I had the idea that we implement the same `class.staticMethod` structure for the `TypeDescriptionWithClassloader`, so that the access to the `of` method is differently for loaded and for unloaded types.

e.g., by implementing nested classes with names such as `ForLoadedType` and `ForUnloadedType` and then have these two classes implement the `of` method
</blockquote></details>

nice idea, not implemented.


<!-- Sent from Reviewable.io -->

2022-11-14 14:13 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1501)* status: all files reviewed, 1 unresolved discussion (waiting on @ClaudioWaldvogel and @MariusBrill)



<!-- Sent from Reviewable.io -->

2022-11-14 14:15 UTC, merged