Closes #1425 - Migrate Release Pipeline to GitHub Actions
inspectIT/inspectit-ocelot pull request #1516
Opened 2022-09-01 09:49 UTC by aaronweissler

Closes #1425

2022-09-01 09:55 UTC, aaronweissler reviewed
Depends on new `release` environment with Docker login data and a protection rule so releases are only created with explicit approval.

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-:-NAsT08VAGFYgkXwQrZf:baiz4wg)* status: 0 of 10 files reviewed, 2 unresolved discussions

___
*[`.github/workflows/release.yml` line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NAsSurwCynBCvTOQhiT:-NAsSurwCynBCvTOQhiU:b5n5ipz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/3681ee3114c46d84a0ec7a50c6e9d8f935e097c9/.github/workflows/release.yml#L26)):*
> ```YAML
>     runs-on: ubuntu-latest
>     environment: release
>     needs: [agent_test, configdocsgenerator_test, configurationserver_test, configuration_ui_test]
> ```

Open question:
Do we want to run all tests once more when triggering a release?

I personally feel like it is not necessary, since the tests are already run on every commit to the master anyways, and then they just take up time for the release, especially if one of them fails randomly, like some of them do at times right now.
___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 168 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NAsSp-oCGuME4akRk3_:-NAsSp-oCGuME4akRk3a:br65ij3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/3681ee3114c46d84a0ec7a50c6e9d8f935e097c9/components/inspectit-ocelot-configurationserver/build.gradle#L168)):*
> ```Gradle
>     dependsOn copyServerJar
> 
>     tag 'versioned', "hub.docker.com/${name}:${version}"
> ```

`tags` is deprecated in favor of `tag`


<!-- Sent from Reviewable.io -->

2022-09-05 08:14 UTC, aaronweissler commented
When merging, CircleCI must be deactivated in the [project's settings](https://app.circleci.com/settings/project/github/inspectIT/inspectit-ocelot).

2022-09-12 08:28 UTC, aaronweissler commented
Currently Releases would be shown as created by `github-actions` user, if we want it to be by a specific user, e.g. `NTTechnicalUser` I think we need to just provide a personal access token of his to the release action, but the docs are not entirely clear on that, so we should test that once if wanted.

2022-09-12 08:33 UTC, aaronweissler commented
Draft until `NTTechnicalUser` as releasing user

2022-09-12 09:49 UTC, aaronweissler commented
Token has been added to code and environment secrets and functionality has been tested in fork.

2022-11-21 08:11 UTC, heiko-holz requested changes
> Reviewed 9 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 7 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/agent_test.yml` line 19 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHODEAyEEPFBOpbXeyD:-NHODEAyEEPFBOpbXeyE:b-lgct08) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/agent_test.yml#L19)):*
> ```YAML
>       - '.github/**'
>       - '.circleci/**'
>   workflow_call:
> ```

do we need this `workflow_call` (also in the other files) so that `release.yml` can use it?
___
*[`.github/workflows/deploy_master_docs.yml` line 1 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBbtPE7V-VyDFcCko:-NHOBbtPE7V-VyDFcCkp:b-5ijx8n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L1)):*
> ```YAML
> name: Deploy Master Documentation
> ```

this does not release a versioned documentation, right?
___
*[`.github/workflows/deploy_master_docs.yml` line 22 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOAO1U6VOcP-VADPeq:-NHOAO1U6VOcP-VADPer:bgliswk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L22)):*
> ```YAML
>         uses: actions/checkout@v3
>       - name: Set up Node.js
>         uses: actions/setup-node@v2
> ```

in the `docs_deployment_test.yml`, we are using `actions/setup-node@v3`
___
*[`.github/workflows/docs_deployment_test.yml` line 16 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOAHPv2Fr5qfn1fy_F:-NHOAHPv2Fr5qfn1fy_G:bi8ib5c) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/docs_deployment_test.yml#L16)):*
> ```YAML
>         working-directory: inspectit-ocelot-documentation/website
>     steps:
>       - uses: actions/checkout@v2
> ```

in the `deploy_master_docs.yml`, we are using `actions/checkout@v3`
___
*[`.github/workflows/release.yml` line 89 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBTBZDubVxRa3wQeh:-NHOBTBZDubVxRa3wQei:b-t92t5e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L89)):*
> ```YAML
>         uses: actions/checkout@v3
>       - name: Setup Node.js
>         uses: actions/setup-node@v2
> ```

can we use `actions/setup-node@v3`?


<!-- Sent from Reviewable.io -->

2022-11-28 09:40 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 8 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/release.yml` line 73 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHxakpF5gaprPAX0FXR:-NHxakpF5gaprPAX0FXS:br1evxc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L73)):*
> ```YAML
>         run: |
>           docker login -u ${{ secrets.DOCKER_HUB_USER }} -p  ${{ secrets.DOCKER_HUB_PASSWORD }}
>           docker push aaronweikru/inspectit-ocelot-agent:${{ github.ref_name }}
> ```

before accepting the pull request, we need to change this to the inspectIT Ocelot main repository
___
*[`.github/workflows/release.yml` line 89 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBTBZDubVxRa3wQeh:-NHxZ6uo8Eqh-acqA9GW:b-ev5smp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L89)):*
> setup-node@v3?


<!-- Sent from Reviewable.io -->

2022-12-16 18:42 UTC, danipaniii reviewed
Unfortunately I cannot push to Aarons branch, so I made a branch on my fork and implemented the above mentioned changes.

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-:-NJRELGsCanhCmmNEUls:bmohz7l)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @aaronweissler, @Dimi-Ma, and @heiko-holz)

___
*[`.github/workflows/agent_test.yml` line 19 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHODEAyEEPFBOpbXeyD:-NJR0gOEErLdeajLBHiH:bb77ufg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/agent_test.yml#L19)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need this `workflow_call` (also in the other files) so that `release.yml` can use it?
</blockquote></details>

Yes.
___
*[`.github/workflows/deploy_master_docs.yml` line 1 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBbtPE7V-VyDFcCko:-NJREWwXBeE68N-Pvw0A:b7905yv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L1)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

this does not release a versioned documentation, right?
</blockquote></details>

I will try out.
___
*[`.github/workflows/deploy_master_docs.yml` line 22 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOAO1U6VOcP-VADPeq:-NJR2DZuCZhBFFPjkbCf:b-7h16bc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L22)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

in the `docs_deployment_test.yml`, we are using `actions/setup-node@v3`
</blockquote></details>

Indeed, it probably won't affect the result for now, but it is better to keep things consistent, so I will change it.
___
*[`.github/workflows/docs_deployment_test.yml` line 16 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOAHPv2Fr5qfn1fy_F:-NJR3GFx359EaWCME-ll:b5wg91f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/docs_deployment_test.yml#L16)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

in the `deploy_master_docs.yml`, we are using `actions/checkout@v3`
</blockquote></details>

I also updated it here, to stay consistent.
___
*[`.github/workflows/release.yml` line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NAsSurwCynBCvTOQhiT:-NJR3dkPBzzlVMnvl41y:b-cxr0a) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/3681ee3114c46d84a0ec7a50c6e9d8f935e097c9/.github/workflows/release.yml#L26)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Open question:
Do we want to run all tests once more when triggering a release?

I personally feel like it is not necessary, since the tests are already run on every commit to the master anyways, and then they just take up time for the release, especially if one of them fails randomly, like some of them do at times right now.
</blockquote></details>

I agree with Aaron, that running the tests when triggering a release is not really necessary.
___
*[`.github/workflows/release.yml` line 73 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHxakpF5gaprPAX0FXR:-NJR43EzENuaxIjFhq4P:b4frqmp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L73)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

before accepting the pull request, we need to change this to the inspectIT Ocelot main repository
</blockquote></details>

Are the secrets already set to login into Dockerhub?
___
*[`.github/workflows/release.yml` line 89 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBTBZDubVxRa3wQeh:-NJR4NRJ0H811_aKl-KM:b-hg1yk6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L89)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

> setup-node@v3?
</blockquote></details>

Yes, I changed it.


<!-- Sent from Reviewable.io -->

2023-01-02 07:26 UTC, heiko-holz requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronweissler, @danipaniii, and @Dimi-Ma)

___
*[`.github/workflows/agent_test.yml` line 19 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHODEAyEEPFBOpbXeyD:-NKlMvhq0tGtcqpCkVrf:b2nid0f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/agent_test.yml#L19)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

thx
___
*[`.github/workflows/release.yml` line 73 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHxakpF5gaprPAX0FXR:-NKlMp2S75bxy78cGBrm:b-g76y67) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L73)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Are the secrets already set to login into Dockerhub?
</blockquote></details>

Good question, I don't know as I've never worked with the Dockerhub :(


<!-- Sent from Reviewable.io -->

2023-01-02 07:27 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronweissler, @danipaniii, and @Dimi-Ma)

___
*[`.github/workflows/release.yml` line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NAsSurwCynBCvTOQhiT:-NHO7KZ7Dzx9H31ZO4zl:b4xtr8p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/3681ee3114c46d84a0ec7a50c6e9d8f935e097c9/.github/workflows/release.yml#L26)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Open question:
Do we want to run all tests once more when triggering a release?

I personally feel like it is not necessary, since the tests are already run on every commit to the master anyways, and then they just take up time for the release, especially if one of them fails randomly, like some of them do at times right now.
</blockquote></details>

I would agree. 
But only if we cannot start a release before the tests on the main branch have passed (as they are triggered after the commit). If we can also start the release without waiting for the tests after the last commit, I would still have the tests in the release ...


<!-- Sent from Reviewable.io -->

2023-01-02 07:27 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 5 unresolved discussions (waiting on @aaronweissler, @danipaniii, and @Dimi-Ma)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NKlNC7-CcDuchEn3Oae:-NKlNC7-CcDuchEn3Oaf:b-8xne6w) (no related file):*
As far as I can see you were able to push to Aaron's branch, right?

___


<!-- Sent from Reviewable.io -->

2023-01-02 09:25 UTC, aaronweissler reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 4 unresolved discussions (waiting on @Dimi-Ma and @heiko-holz)

___
*[`.github/workflows/deploy_master_docs.yml` line 1 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBbtPE7V-VyDFcCko:-NKlk1a75S9z8Hvau3L9:b-k50jvx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L1)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I will try out.
</blockquote></details>

Just in case this hasn't been answered yet, yes, this action is only for updating the master branch version of the documentation. The versioned documentation is generated only for releases in the build_documentation step of the release action.
___
*[`.github/workflows/release.yml` line 73 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHxakpF5gaprPAX0FXR:-NKlkpO2Ei6kqL1uNnip:bolqowm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/release.yml#L73)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Good question, I don't know as I've never worked with the Dockerhub :(
</blockquote></details>

Unless the login data changed since then, yes they are set up. You can see the secrets (DOCKER_HUB_USER and DOCKER_HUB_PASSWORD) in the release environment in the project settings.


<!-- Sent from Reviewable.io -->

2023-01-02 10:10 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/deploy_master_docs.yml` line 1 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NHOBbtPE7V-VyDFcCko:-NKlxMsyAgC2H-bHjmNr:b8dyytw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/76e5b42b9a35d35202e1a1906626e9daa89b3431/.github/workflows/deploy_master_docs.yml#L1)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Just in case this hasn't been answered yet, yes, this action is only for updating the master branch version of the documentation. The versioned documentation is generated only for releases in the build_documentation step of the release action.
</blockquote></details>

Thanks @aaronweissler for your clarification!


<!-- Sent from Reviewable.io -->

2023-01-16 10:49 UTC, danipaniii commented
When trying to make a test-release I encounter two errors:
1. Pushing the docker image results in the error message ```Cannot perform an interactive login from a non TTY device```. Which may result because of the wrong credentials. Another answer from the internet suggested that it is because the ```$DOCKER_TAG```environmental isn't set. But trying to set the variable did not fix the problem.
2. When creating a new documentation results in the error message ```pathspec 'master' did not match any file(s) known to git``` 

At the moment I have actions running, trying to fix the above mentioned error messages.
For more information on how to maybe fixing the 2. issue I found the following stack overflow post: [https://stackoverflow.com/questions/5989592/git-cannot-checkout-branch-error-pathspec-did-not-match-any-files-kn](url).

2023-01-23 11:39 UTC, danipaniii commented
I could fix the issue with creating the documentation and I started to implement the docker github action from the ocelot eum server, because I run into more errors with the login with the previous action. 
Unfortunately when building the docker image I get the following error: 
![Screenshot from 2023-01-23 12-34-53](https://user-images.githubusercontent.com/110303840/214030481-5f155adf-376a-4ff0-9fae-6fd872a57ba4.png)

2023-01-31 11:59 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/release.yml` line 12 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NN6GHcU-0YyL4pKL0jl:-NN6GHcU-0YyL4pKL0jm:bfufkqs) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/497178352425bc75a6858c33ae09de8e9c2f2af1/.github/release.yml#L12)):*
To be consistent with previous releases, let's change
> New Features 🎉

to


> Implemented Enhancements 🎉


<!-- Sent from Reviewable.io -->

2023-02-08 22:48 UTC, heiko-holz requested changes
> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/changelog-release-config.json` line 4 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnARNm-NJQjgUdXYvG:-NNnARNm-NJQjgUdXYvH:bh3jd6u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/changelog-release-config.json#L4)):*
> ```JSON
>     "categories": [
>         {
>             "title": "## 🛠 Breaking Changs",
> ```

missing "e" in "Chang**e**s"
___
*[`.github/workflows/changelog-release-config.json` line 24 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnAd8M1T1h3GEhqWop:-NNnAd8M1T1h3GEhqWoq:b-6a9peh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/changelog-release-config.json#L24)):*
> ```JSON
>         }
>     ],
>     "sort": "ASC",
> ```

what are the sorting options?
Previously, we have sorted by the closing date
___
*[`.github/workflows/release.yml` line 55 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnBV5r82Og9gcV9Qa2:-NNnBV5r82Og9gcV9Qa3:bvjzvib) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/065693ac7ba52ba41ef9713a5941d444a67cf348/.github/workflows/release.yml#L55)):*
> ```YAML
>           token: ${{ secrets.RELEASE_USER_TOKEN }}
>           name: Version ${{ github.ref_name }}
>           body: "You can also find the corresponding documentation online under the following link: [inspectIT Ocelot Documentation](http://docs.inspectit.rocks)"
> ```

is this sentence also present in the new changelog?
___
*[`.github/workflows/release.yml` line 81 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnBk0Q3JRC4bx4Cy3B:-NNnBk0Q3JRC4bx4Cy3C:bevveyv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/release.yml#L81)):*
> ```YAML
>       - name: Checkout
>         uses: actions/checkout@v3
>       # Downloading jars to create docker image
> ```

Why are the longer steps needed to publish to docker?

What didn't work with Aaron's original approach (which is way shorter).

Aaron was using the `docker` tasks in the agent's `build.gradle` file. 


<!-- Sent from Reviewable.io -->

2023-02-08 22:54 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/release.yml` line 81 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnBk0Q3JRC4bx4Cy3B:-NNnE6KO-fouq_Ln9P9f:b-e4mv0n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/release.yml#L81)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Why are the longer steps needed to publish to docker?

What didn't work with Aaron's original approach (which is way shorter).

Aaron was using the `docker` tasks in the agent's `build.gradle` file. 
</blockquote></details>

let's discuss this in our next meeting


<!-- Sent from Reviewable.io -->

2023-02-09 10:53 UTC, heiko-holz requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: 10 of 14 files reviewed, 9 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`components/inspectit-ocelot-configurationserver/docker/Dockerfile` line 3 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNozcMcBFJZKWk4KNFA:-NNozcMcBFJZKWk4KNFB:bkjnenx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/components/inspectit-ocelot-configurationserver/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM openjdk:11-jre-slim
> 
> ADD ./components/inspectit-ocelot-configurationserver/docker/  /
> ```

I have found the problem why you couldn't run the gradle task: the current directory is already the `/components/inspectit-ocelot-configurationserver/docker` when executing the gradle task and the `Dockerfile`, 

thus, this line needs to be changed to 
 `./ /`
if we are using the `gradlew docker` tasks



_Code quote:_
```Dockerfile
COPY
```
___
*[`inspectit-ocelot-agent/docker/Dockerfile` line 3 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNozvBf2MFnWebUMu9C:-NNozvBf2MFnWebUMu9D:b-euzqzo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/inspectit-ocelot-agent/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM busybox
> 
> ADD ./inspectit-ocelot-agent/docker/  /
> ```

I have found the problem why you couldn't run the gradle task: the current directory is already the `/inspectit-ocelot-agent/docker` when executing the gradle task and the `Dockerfile`, 

thus, this line needs to be changed to 
 `./ /`
if we are using the `gradlew docker` tasks


<!-- Sent from Reviewable.io -->

2023-02-10 11:49 UTC, danipaniii reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516)* status: 9 of 14 files reviewed, 9 unresolved discussions (waiting on @aaronweissler, @Dimi-Ma, and @heiko-holz)

___
*[`.github/workflows/changelog-release-config.json` line 4 at r7](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516#-NNnARNm-NJQjgUdXYvG:-NNv2zAJAWsEiYnMVfMY:bb6un1j) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/changelog-release-config.json#L4)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

missing "e" in "Chang**e**s"
</blockquote></details>

Done
___
*[`.github/workflows/changelog-release-config.json` line 24 at r7](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516#-NNnAd8M1T1h3GEhqWop:-NNv8ImB58sOqFjtI2BT:b-520t9i) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/changelog-release-config.json#L24)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

what are the sorting options?
Previously, we have sorted by the closing date
</blockquote></details>

You can sort on ascending or descending order and based either on 'mergedAt' or by 'title'. The default is mergedAt.
___
*[`.github/workflows/release.yml` line 55 at r4](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516#-NNnBV5r82Og9gcV9Qa2:-NNv3CKvDyrQCR-uX9Rp:b-ygj6ts) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/065693ac7ba52ba41ef9713a5941d444a67cf348/.github/workflows/release.yml#L55)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

is this sentence also present in the new changelog?
</blockquote></details>

It wasn't so I added it now.
___
*[`.github/workflows/release.yml` line 81 at r7](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516#-NNnBk0Q3JRC4bx4Cy3B:-NNv7dQJ1k6TLU2zYcZG:bv9rtb2) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/release.yml#L81)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

let's discuss this in our next meeting
</blockquote></details>

There were the errors with the login and the Dockerfile couldn't find the necessary files to create the image.
The reason for why the login failed, was because no login credentials where set, unfortunately the error message on that was a little misleading.
The solution for the other error you have figured out.
___
*[`components/inspectit-ocelot-configurationserver/docker/Dockerfile` line 3 at r7](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1516#-NNozcMcBFJZKWk4KNFA:-NNv3U3O7eHiNKAxgugj:bggtm15) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/components/inspectit-ocelot-configurationserver/docker/Dockerfile#L3)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I have found the problem why you couldn't run the gradle task: the current directory is already the `/components/inspectit-ocelot-configurationserver/docker` when executing the gradle task and the `Dockerfile`, 

thus, this line needs to be changed to 
 `./ /`
if we are using the `gradlew docker` tasks
</blockquote></details>

Yes, this fixed the problem!


<!-- Sent from Reviewable.io -->

2023-02-10 13:10 UTC, heiko-holz reviewed
> Reviewed 1 of 3 files at r6, 2 of 2 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`.github/workflows/changelog-release-config.json` line 24 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NNnAd8M1T1h3GEhqWop:-NNvJX113SWFvuMJjG_w:b-8zod71) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9a3386f1de4676e5ade00656af5eddf599e03ab3/.github/workflows/changelog-release-config.json#L24)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

You can sort on ascending or descending order and based either on 'mergedAt' or by 'title'. The default is mergedAt.
</blockquote></details>

Alright, thanks for clarifying!


<!-- Sent from Reviewable.io -->

2023-02-10 13:12 UTC, heiko-holz reviewed
> Reviewed 1 of 3 files at r7, all commit messages.
> Dismissed @aaronweissler from a discussion.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)

___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 168 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NAsSp-oCGuME4akRk3_:-NNvS5m74z8fucRLLNnf:b2nhysk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/3681ee3114c46d84a0ec7a50c6e9d8f935e097c9/components/inspectit-ocelot-configurationserver/build.gradle#L168)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

`tags` is deprecated in favor of `tag`
</blockquote></details>

ack


<!-- Sent from Reviewable.io -->

2023-02-10 13:22 UTC, heiko-holz reviewed
> Reviewed 4 of 11 files at r10, 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronweissler and @Dimi-Ma)



<!-- Sent from Reviewable.io -->

2023-02-10 13:42 UTC, heiko-holz approved these changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @Dimi-Ma)



<!-- Sent from Reviewable.io -->

2023-02-10 13:43 UTC, heiko-holz approved these changes
> Dismissed @aaronweissler from a discussion.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Dimi-Ma)



<!-- Sent from Reviewable.io -->

2023-02-10 14:50 UTC, merged