Closes ##1506 - Evaluate the new Nova theme when updating Primereact to version 8 #1506
inspectIT/inspectit-ocelot pull request #1517
Opened 2022-09-01 16:39 UTC by salim-1997

Closes  #1506
* Update primereact
* Reframe components with CSS
* fix Dialog creation erros

2022-09-19 11:11 UTC, aaronweissler reviewed
The filtering on the Agent Mappings page seems to be broken somehow, the default mapping shows up often when it shouldn't and when removing input the previously filtered Mappings do not re-appear anymore.

The "Combine duplicate services" should not have a linebreak in it and be closer to "Use Regex" as before. 
See old vs. new version below:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/46028218/4rqO1yqSFpCPLL4DMG6sq4c9/image.png)
![image.png](https://files.reviewableusercontent.io/images/reviewable/46028218/dFNxzShll8jIazKzqEeG9EY8/image.png)

It also seems like all the text is slightly smaller/thinner, I personally prefer the old version, see also old vs new of other text:
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/46028218/U0NToUT6APVpn4c197laSm_T/image.png)
![image copy 3.png](https://files.reviewableusercontent.io/images/reviewable/46028218/uTzw-Fwf9PwHebkTjE5XFGAk/image.png)

A lot of the buttons creating dialogs where input fields are supposed to be focused are broken, for example:
- search dialog in Configuration View:
![image copy 4.png](https://files.reviewableusercontent.io/images/reviewable/46028218/FFI53uVIXHWli2WAfZ7LM71b/image.png)
- creating a new folder dialog:
![image copy 5.png](https://files.reviewableusercontent.io/images/reviewable/46028218/ZTs4F4YpPn1PjILuwM2nLN3C/image.png)
- creating a new folder dialog with changing it like you did in the other case with one of those `timeout` expressions also does not fix it. On the first try, it just does not do anything, which is not correct, since it should focus the input field. On clicking the dialog a second time it crashes, as `this.input.current` is not undefined anymore but `this.input.current.element` still is :
![image copy 6.png](https://files.reviewableusercontent.io/images/reviewable/46028218/CM_azotq94OgGwdsl0uZHLP-/image.png)

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-:-NCKJ-oP8-XvmW4UCtna:bn9mpcm)* status: 0 of 39 files reviewed, all discussions resolved (waiting on @aaronweissler)



<!-- Sent from Reviewable.io -->

2022-09-19 11:38 UTC, aaronweissler requested changes
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 0 of 39 files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js` line 103 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NCKXTYX45p9btTtaa-y:-NCKXTYX45p9btTtaa-z:b-pvdbuv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/98c186bdddced0e5f03728d137804bf4610cd3fa/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js#L103)):*
> ```JavaScript
>   componentDidUpdate(prevProps) {
>     if (!prevProps.visible && this.props.visible) {
>       if (this.input.current) {
> ```

Similarly to the last screenshot showing the error when trying to create a new folder, this also either does not do anything or leads to an error


<!-- Sent from Reviewable.io -->

2022-10-17 12:19 UTC, danipaniii reviewed
> Reviewed 9 of 39 files at r5, 3 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 34 of 39 files reviewed, 5 unresolved discussions (waiting on @aaronweissler and @salim-1997)



<!-- Sent from Reviewable.io -->

2022-10-28 16:47 UTC, danipaniii reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 31 of 48 files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/tree/AlertingChannelsTreeToolbar.js` line 69 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NE_mF66921nWzMe1Eeu:-NFUSA6N3D8exzIu2LwI:b-tzkgu6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dba9fa210918549c02078e82f8925ff47024ca22/components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/tree/AlertingChannelsTreeToolbar.js#L69)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

When the dialog is shown a error message appears. The error occurs when focusing the delete button in configuration\DeleteDialog.js line 47 "this" is undefinded and the button doesn't focus. Still the deleting of the files works fine.
</blockquote></details>

I have fixed the issue
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js` line 95 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NE_nU-91chANE4Br4pI:-NFUSGkZ25aWouaqhic8:b-k8h47a) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dba9fa210918549c02078e82f8925ff47024ca22/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js#L95)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Same error as mentioned above with the DeleteDialog.js file in configuration\DeleteDialog.js 
</blockquote></details>

I fixed the issue and the button focuses as expected.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/dialogs/PromotionApprovalDialog.js` line 41 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NE_pn3P3OBrYmCe2efq:-NFUUIdl83cQ7EO7Q7Ft:b-lirlk8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dba9fa210918549c02078e82f8925ff47024ca22/components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/dialogs/PromotionApprovalDialog.js#L41)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Focus doesn't get set to the messageInput.
</blockquote></details>

I have solved this issue.


<!-- Sent from Reviewable.io -->

2022-10-31 08:30 UTC, danipaniii submitted a review, later dismissed

2022-11-04 12:37 UTC, danipaniii commented
At the moment there are two more warnings left, I am not able to resolve at the moment.
<img width="534" alt="setCapture_deprecated_problem" src="https://user-images.githubusercontent.com/110303840/199972707-95640ef6-9f24-4448-b14c-b0658ae241da.png">
In our files we don't use any of those methods `setCapture` or `releaseCaputre`, maybe we are using a library with a text area editor component, that still uses those deprecated methods. At least that's my guess for now. Since we want to implement a multiple tab editor in the future and  therefore using a new primereact component, I would look over that warning at the moment.

<img width="558" alt="weird_next_issue" src="https://user-images.githubusercontent.com/110303840/199973575-8f49aa1e-86f8-43b9-8641-b92979289279.png">
This error gets generated through files that are being created by next. I couldn't find anything on the internet about this issue. Still I couldn't notice any undesired behavior of the UI so far.

2022-11-10 08:55 UTC, heiko-holz requested changes
> Reviewed 3 of 22 files at r8, 1 of 3 files at r9, 12 of 12 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 3 unresolved discussions (waiting on @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver-ui/next.config.js` line 6 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXfl0-TJoKjtkMJut:-NGVXfl0-TJoKjtkMJuu:b-gg5lv6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/next.config.js#L6)):*
> ```JavaScript
> module.exports = withCSS({
>     distDir: '../.next',
>     basePath: '/',
> ```

could you add the comment (to the source file) why the `basePath` is set?

Actually, I receive the following error when trying to `yarn dev`:

```
yarn run v1.22.19
$ next ./src
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error: Specified basePath /. basePath has to be either an empty string or a path prefix"
    at assignDefaults (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\config.js:5:1360)
    at loadConfig (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\config.js:7:1101)
    at new Server (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\next-server.js:1:4199)
    at new DevServer (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\next-dev-server.js:1:2964)
    at createServer (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\next.js:2:607)
    at start (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\lib\start-server.js:1:323)
    at nextDev (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\cli\next-dev.js:20:1776)
    at C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\bin\next:26:341

```
___
*[`components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz` line 0 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYfK4DDcrDrBp6NeS:-NGVYfK4DDcrDrBp6NeT:b-qj3o9f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz#L0)):*
file can be deleted (as we did for other features)
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js` line 42 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXzvK7fGY-mmeJipR:-NGVXzvK7fGY-mmeJipS:b-kc168j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js#L42)):*
> ```JavaScript
>   componentDidUpdate(prevProps) {
>     if (!prevProps.visible && this.props.visible) {
>       //this.deleteButton.current.focus(); -> caused an error, because the delete button cannot be focused beforehand, could be fixed with autoFocus
> ```

this is fixed by the `autofocus={true}` property, right?

Then we could delete this comment here
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js` line 81 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYBMo7farBH9XfIn6:-NGVYBMo7farBH9XfIn7:b-3lwoxg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/95005fc5fc8125700447a094f56ae3db285e31a3/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js#L81)):*
> ```JavaScript
>       /**Timeout is needed for .focus() to be triggered correctly. */
>       setTimeout(() => {
>         this.downloadButton.current.element.focus();
> ```

was it necessary to remove `.element`?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js` line 46 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYMsm6iCh6XO78PLS:-NGVYMsm6iCh6XO78PLT:b-4pe8pe) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/95005fc5fc8125700447a094f56ae3db285e31a3/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js#L46)):*
> ```JavaScript
>           }
>           .this :global(.p-tabmenu-nav .p-tabmenuitem .p-menuitem-link) {
>             background-color: #b6b6b6;
> ```

why was this background color removed?

Does it now come with the new prime react version?


<!-- Sent from Reviewable.io -->

2022-11-11 09:52 UTC, danipaniii reviewed
I'll take a look at this warning and try to fix it.

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-:-NGa5diw1o42Yw1gC6UP:b4o4pxc)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver-ui/next.config.js` line 6 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXfl0-TJoKjtkMJut:-NG_xnzs7Dhos5VG8wNC:b7mb9ny) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/next.config.js#L6)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

could you add the comment (to the source file) why the `basePath` is set?

Actually, I receive the following error when trying to `yarn dev`:

```
yarn run v1.22.19
$ next ./src
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error: Specified basePath /. basePath has to be either an empty string or a path prefix"
    at assignDefaults (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\config.js:5:1360)
    at loadConfig (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\config.js:7:1101)
    at new Server (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\next-server\server\next-server.js:1:4199)
    at new DevServer (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\next-dev-server.js:1:2964)
    at createServer (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\next.js:2:607)
    at start (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\server\lib\start-server.js:1:323)
    at nextDev (C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\cli\next-dev.js:20:1776)
    at C:\Users\HHO\dev\inspectit\review\mmh\inspectit-ocelot-mmh\components\inspectit-ocelot-configurationserver-ui\node_modules\next\dist\bin\next:26:341

```
</blockquote></details>

Interestingly I receive the same error message now, I will work on it.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js` line 42 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXzvK7fGY-mmeJipR:-NG_yzex7oiG34AHraYU:b-a31nn6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js#L42)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

this is fixed by the `autofocus={true}` property, right?

Then we could delete this comment here
</blockquote></details>

Exactly and since the componentDidUpdate method doesn't do anything else at the moment, should we remove it?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js` line 81 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYBMo7farBH9XfIn6:-NG_z8ML72Pr4xPshMpU:bb77ufg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/95005fc5fc8125700447a094f56ae3db285e31a3/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js#L81)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

was it necessary to remove `.element`?
</blockquote></details>

Yes.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js` line 46 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYMsm6iCh6XO78PLS:-NGa-N1h-OfqHmpEYvD4:b1twb9d) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/95005fc5fc8125700447a094f56ae3db285e31a3/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js#L46)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why was this background color removed?

Does it now come with the new prime react version?
</blockquote></details>

I don't remember removing the background color.
Also it has no visible effect to me, whether this color styling is there or not.
I will just put it in again, because it looks like it wasn't removed for any meaningful purpose.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js` line 103 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NCKXTYX45p9btTtaa-y:-NGa0-pp900QrHw9BoG3:b-3m4b7h) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/98c186bdddced0e5f03728d137804bf4610cd3fa/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js#L103)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Similarly to the last screenshot showing the error when trying to create a new folder, this also either does not do anything or leads to an error
</blockquote></details>

This has been fixed


<!-- Sent from Reviewable.io -->

2022-11-11 11:11 UTC, danipaniii commented
While working on another issue, I noticed that this error message: 
<img width="558" alt="weird_next_issue" src="https://user-images.githubusercontent.com/110303840/201328209-9123a412-c73f-4474-97bc-050c26cee2cc.png">
Occurs especially with empty .yml files. When the .yml files aren't empty this message doesn't show. Maybe someone can make a similar observation.

2022-11-21 07:21 UTC, heiko-holz requested changes
> Reviewed 3 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 49 of 50 files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js` line 42 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXzvK7fGY-mmeJipR:-NHO2tmR9a3svj4GMF3X:bb1lcox) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DeleteDialog.js#L42)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Exactly and since the componentDidUpdate method doesn't do anything else at the moment, should we remove it?
</blockquote></details>

Yes, we should remove all unnecessary code
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js` line 46 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVYMsm6iCh6XO78PLS:-NHO3-PD2dNKYJm8paLC:bd5l6mr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/95005fc5fc8125700447a094f56ae3db285e31a3/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/SettingsMenu.js#L46)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I don't remember removing the background color.
Also it has no visible effect to me, whether this color styling is there or not.
I will just put it in again, because it looks like it wasn't removed for any meaningful purpose.
</blockquote></details>

thanks!


<!-- Sent from Reviewable.io -->

2022-11-21 07:28 UTC, heiko-holz commented
@danipaniii: 

I receive the same exception when I click on empty files:

```
GEThttp://localhost:3000/_next/8f7cd49ef21ef2849cb21408fd2cef2e.js
[HTTP/1.1 404 Not Found 15ms]

Loading script from “http://localhost:3000/_next/8f7cd49ef21ef2849cb21408fd2cef2e.js” with importScripts() was blocked because of a disallowed MIME type (“text/html”).
```

However, the following warning message is triggered for each file when I right-click on it:
![image](https://user-images.githubusercontent.com/12088200/202990107-ef7cf3d8-ffa1-4d98-adba-907683abf433.png)

2022-11-21 10:46 UTC, heiko-holz reviewed
> Reviewed 1 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @danipaniii)



<!-- Sent from Reviewable.io -->

2022-11-22 16:08 UTC, danipaniii reviewed
Regarding the warning message when right-clicking:
I tried to identify the source of the problem and fix it. Unfortunately I personally don't have any idea at the moment.
Looking at the stacktrace the source of the problem seems to be in this line:
![errorOrigin.png](https://files.reviewableusercontent.io/images/reviewable/110303840/VM15Fuafu4G79JrQvJdsJZVZ/errorOrigin.png)
And the error seems to occur in the ref part. Looking at the two warning messages that get fired when right-clicking, I thought that the reference is accessing the pageX and pageY properties.
![errorMessage1.png](https://files.reviewableusercontent.io/images/reviewable/110303840/fGbZh9Q6h16OElWHZNnfaCfZ/errorMessage1.png)
![errorMessage2.png](https://files.reviewableusercontent.io/images/reviewable/110303840/Qlu-2qlZ00vE7einx3blQ3XS/errorMessage2.png)
So I took a closer look at the referencing part and console.logged it:
![ContextMenuRefOP.png](https://files.reviewableusercontent.io/images/reviewable/110303840/kybu5qLdobz_-2ULuMI4CjzN/ContextMenuRefOP.png)
However I cannot find the pageX and pageY properties. So I thought the problem might be laying somewhere at the ContextMenu component. But everything was done according to the documentation. You can check here: https://www.primefaces.org/primereact/contextmenu/ . The only difference in the example from the documentation is that there they use the useRef hook, but note that hooks can just be used in functions and not inside the state property (See: https://reactjs.org/docs/hooks-rules.html). 

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-:-NHV1klq1-J0kiOQ4wiJ:b7likza)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronweissler and @heiko-holz)



<!-- Sent from Reviewable.io -->

2022-11-28 09:15 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronweissler and @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/next.config.js` line 6 at r15](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NGVXfl0-TJoKjtkMJut:-NHxW9thE-rUWD9EAbdh:b-ldwaho) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/12c196348e6768d76d25af1b0c1b2d63f56562f2/components/inspectit-ocelot-configurationserver-ui/next.config.js#L6)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Interestingly I receive the same error message now, I will work on it.
</blockquote></details>

We removed the `basePath` as this didn't lead to any solution


<!-- Sent from Reviewable.io -->

2022-11-28 09:16 UTC, heiko-holz reviewed
> Dismissed @aaronweissler from a discussion.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii and @salim-1997)



<!-- Sent from Reviewable.io -->

2022-11-28 09:18 UTC, heiko-holz reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js` line 103 at r9](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NCKXTYX45p9btTtaa-y:-NHxWrc67pC1Lr3tlVG3:b-7h4u3n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/98c186bdddced0e5f03728d137804bf4610cd3fa/components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js#L103)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

This has been fixed
</blockquote></details>

works


<!-- Sent from Reviewable.io -->

2022-11-28 09:18 UTC, heiko-holz submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salim-1997)



<!-- Sent from Reviewable.io -->

2022-12-01 06:18 UTC, heiko-holz approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salim-1997)



<!-- Sent from Reviewable.io -->

2022-12-12 06:37 UTC, heiko-holz requested changes
> Reviewed 4 of 89 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 51 of 136 files reviewed, 4 unresolved discussions (waiting on @danipaniii and @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 15 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41A4AEhT2w87gmUyI:-NJ41A4AEhT2w87gmUyJ:b-riafeq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/build.gradle#L15)):*
> ```Gradle
> node {
>     // Version of node to use.
>     version = '12.16.1'
> ```

didn't we upgrade the node/yarn/jdbc version for a reason?

I think we should keep the higher versions
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java` line 56 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41JkzCuuaMT_tAJWz:-NJ41JkzCuuaMT_tAJX-:b-mm5wtc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java#L56)):*
> ```Java
>      *  Name of the settings states header.
>      */
>     private static final String HEADER_SETTING_STATES = HEADER_PREFIX + "service-states-map";
> ```

I think this re-renaming has been wrongly accepted from master and should be kept to `SERVICE_STATES`
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java` line 109 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41PB15Y6jZBu-qySb:-NJ41PB15Y6jZBu-qySc:b-6gy25e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java#L109)):*
> ```Java
>      * The current setting states in a json string
>      */
>     private String settingStates;
> ```

same here. Should be `serviceStates
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 0 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ42Ado5Mb82WiXOIHE:-NJ42Ado5Mb82WiXOIHF:b91eca8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L0)):*
why w as this file deleted?


<!-- Sent from Reviewable.io -->

2023-01-02 12:13 UTC, heiko-holz submitted a review, later dismissed
> Reviewed 1 of 89 files at r18, 90 of 92 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 15 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41A4AEhT2w87gmUyI:-NKmOeq68ON6ojCJqe3Z:b5gm1aw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/build.gradle#L15)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

didn't we upgrade the node/yarn/jdbc version for a reason?

I think we should keep the higher versions
</blockquote></details>

was fixed
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java` line 56 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41JkzCuuaMT_tAJWz:-NKmNtpxAbibxgi03Nhv:b5gm1aw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java#L56)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think this re-renaming has been wrongly accepted from master and should be kept to `SERVICE_STATES`
</blockquote></details>

was fixed
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java` line 109 at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ41PB15Y6jZBu-qySb:-NKmNuqE4VPelRAeY8FA:b5gm1aw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentMetaInformation.java#L109)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

same here. Should be `serviceStates
</blockquote></details>

was fixed
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line  at r18](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NJ42Ado5Mb82WiXOIHE:-NKmNyaOAex0dl08-_th:b5gm1aw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c5cad5096aed3237c4e3a348134b905ed5b42d01/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why w as this file deleted?
</blockquote></details>

was fixed


<!-- Sent from Reviewable.io -->

2023-01-02 12:44 UTC, heiko-holz commented
I think everything is fixed now.
However, I'd like to have a final chat with @danipaniii to discuss if this is really the case :)





<!-- Sent from Reviewable.io -->

2023-02-21 15:12 UTC, danipaniii reviewed
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: 130 of 136 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @salim-1997)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js` line 226 at r23](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NOoSMQDCVNLNd2h8JGZ:-NOoSMQEEjQaAaI02yZQ:b-sarsb8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0725c32aa76c78a81252825d1a1c15c6bea77961/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js#L226)):*
> ```JavaScript
>       /** primereact/overlaypanel && primereact/tieredMenu must be appended to s.th. 'higher' than the cells components to avoid strange behavoir */
>       <div ref={(el) => (this.mappingsTable = el)}>
>         <DataTable
> ```

This component uses the default styling from the primereact component ```.p-datatable table``` class in which the property ```min-width``` is set to ```100%```, resulting in the data table to be stretched the whole screen and every column get's the same width.
Setting the style of the columns, e.g.```style={{ width: '175px' }}``` does not take any effect in the column size. The ```min-width```  seems to take precedence over the style property in the component.
I tried to overwrite the CSS classes from primereact, just as it was done in the StatusTable.js [See here](https://github.com/inspectIT/inspectit-ocelot/blob/master/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L476-L495), with unfortunately no result.
Nevertheless it was possible to overwrite the ```min-width``` by defining it in the style property of ```DataTable```.
After doing so, the ```width```of the columns could be changed in their style properties, unfortunately it did not change the specific column width, but the width of the whole data table.
At the moment I don't have any additional ideas on how to fix this and I believe that it is nothing that needs to be resolved to merge the PR, but can be fixed in the future.


<!-- Sent from Reviewable.io -->

2023-02-22 07:37 UTC, heiko-holz submitted a review, later dismissed
> Reviewed 2 of 2 files at r21, 3 of 3 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js` line 226 at r23](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NOoSMQDCVNLNd2h8JGZ:-NOoY8Ai3A0y0N3fBOiD:b-coeftd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0725c32aa76c78a81252825d1a1c15c6bea77961/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js#L226)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

This component uses the default styling from the primereact component ```.p-datatable table``` class in which the property ```min-width``` is set to ```100%```, resulting in the data table to be stretched the whole screen and every column get's the same width.
Setting the style of the columns, e.g.```style={{ width: '175px' }}``` does not take any effect in the column size. The ```min-width```  seems to take precedence over the style property in the component.
I tried to overwrite the CSS classes from primereact, just as it was done in the StatusTable.js [See here](https://github.com/inspectIT/inspectit-ocelot/blob/master/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L476-L495), with unfortunately no result.
Nevertheless it was possible to overwrite the ```min-width``` by defining it in the style property of ```DataTable```.
After doing so, the ```width```of the columns could be changed in their style properties, unfortunately it did not change the specific column width, but the width of the whole data table.
At the moment I don't have any additional ideas on how to fix this and I believe that it is nothing that needs to be resolved to merge the PR, but can be fixed in the future.
</blockquote></details>

thanks for the update!

I realized this is all because of the `scrollable={true}`.
This adds the classes `.p-datatable-scrollable`, which adds `flex: 1 1 0` that causes the rows to stretch.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusToolbar.js` line 116 at r23](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NOs26zg1S6AYhfysB_K:-NOs26zg1S6AYhfysB_L:beychn4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0725c32aa76c78a81252825d1a1c15c6bea77961/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusToolbar.js#L116)):*
> ```JavaScript
>               </div>
>               <div className="p-inputgroup checkbox-group">
>                 <label style={{ width: 'max-content' }}>Combine duplicate services</label>
> ```

when applying this, the `?` (hint-badge) icon gets stretched, as the width is set to `width: 1.7rem`.
Maybe changing the `hint-badge` to `width: 20px` does the trick, but I am not sure whether setting an absolute pixel value is favorable.


<!-- Sent from Reviewable.io -->

2023-02-23 07:39 UTC, heiko-holz approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517)* status: all files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js` line 232 at r25](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NOxCFhT6Vv5RTCer6oc:-NOxCFhVEImYc2gKFl91:b-4lbbz3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c571e23850a5e49355ab8a2a992a996a53f579c/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js#L232)):*
> ```JavaScript
>             flex: unset;
>             display: flex;
>             text-align: center;
> ```

I think that this currently takes no effect (`text-align: center)`, does it?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js` line 243 at r25](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-NOxC_IG0bGgZMC5RUH_:-NOxC_IG0bGgZMC5RUHa:b-mf1oyq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c571e23850a5e49355ab8a2a992a996a53f579c/components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js#L243)):*
> ```JavaScript
> 
>           .drag-icon-col {
>             width: 10rem;
> ```

just fyi: the `dag-icon-col` and `buttons-col` are wider due to the `padding` that was not applied in the previous version of primereact


<!-- Sent from Reviewable.io -->

2023-02-23 10:05 UTC, danipaniii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1517#-:-NOxj-Z78IKhUWTA-g8s:bnfp4nl)* status: 133 of 136 files reviewed, all discussions resolved (waiting on @heiko-holz)



<!-- Sent from Reviewable.io -->

2023-02-23 10:07 UTC, heiko-holz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1517#-:-NOxjPbS1Rj4m86-vmed:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @salim-1997)



<!-- Sent from Reviewable.io -->

2023-02-23 11:03 UTC, merged