Vhvapm 444
inspectIT/inspectit-ocelot pull request #1653
Opened 2024-04-15 08:11 UTC by jenniferWitzig

2024-04-18 07:46 UTC, jenniferWitzig commented on inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/tagGuards/PersistedTagsReaderWriterTest.java
> +    }
wird doch aber in Zeile 202 genutzt

2024-04-19 16:38 UTC, EddeCCC requested changes

2024-04-19 16:38 UTC, EddeCCC commented on inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
>          if (!env.getCurrentConfig().getMetrics().getTagGuard().isEnabled()) return;
Hier kannst du auch `isMetrikSettingenable()` nutzen. Wenn ich ganz penibel sein darf: Kannst du die Methode `isTagGuardEnabled()` nennen?

2024-04-19 16:38 UTC, EddeCCC commented on inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
> +    }
Wenn `filename` null oder ein leerer String ist, wird `fileReaderWriter` gar nicht gesetzt.
Dann wird später beim `blockTagValuesTask` ständig eine `NullPointerException` geschmissen wenn `fileReaderWriter.read()` oder `fileReaderWriter.write()` aufgerufen werden.

Was hällst du davon, wenn wir unseren Default-Wert für filename nutzen, wenn vom User null oder ein leerer String kommt?
Also `${inspectit.env.agent-dir}/${inspectit.service-name}/tag-guard-database.json` wobei wir `agent-dir` und `service-name` aus der aktuellen Config auslesen.

2024-04-19 16:38 UTC, EddeCCC commented on inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
> +            log.error("Filename is empty. Not able writign tags.");
Typo

2024-04-19 16:39 UTC, EddeCCC commented on inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/tagGuards/PersistedTagsReaderWriterTest.java
> +    }
Ich meine die @Nested class `ReaderWrite` in `MeasureTagValueGuardTest`.
Da steht der selbe Code drin wie hier

2024-04-19 16:48 UTC, EddeCCC commented on inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
>          if (!env.getCurrentConfig().getMetrics().getTagGuard().isEnabled()) return;
Ich meinte Zeile 95...

2024-05-08 09:13 UTC, TimoF91 requested changes
- nothing to add from my side related to the code 
- have a look at the tests --> it failed (Edit Edi: Probably flaky test)

2024-05-22 06:08 UTC, EddeCCC requested changes
LGTM. Only one small change and it's finished :)

2024-05-22 06:08 UTC, EddeCCC commented on inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
> +        }
Das wird bereits vor `getFilename()` in `isNotWritable()` geprüft. Kann raus.

2024-07-05 07:54 UTC, EddeCCC commented
Merged in https://github.com/inspectIT/inspectit-ocelot/pull/1656

2024-07-05 07:54 UTC, closed without merging